-- Schluessel, Pruefbedingungen und Fremdschluessel der Vorlage
--
-- Uebernommen aus der Vorlage, erzeugt von scripts/neutralisieren.py aus dem
-- woertlichen Schema-Export. Nicht von Hand aendern: die naechste Ausfuehrung
-- des Skripts wuerde die Aenderung verwerfen. Aenderungen gehoeren in das
-- Skript (mit Grund) oder in eine eigene, spaetere Migration.
--
-- Quelle: 20-schluessel.sql, 22-pruefbedingungen.sql, 25-fremdschluessel.sql
--
-- 211 Schluessel, 94 Pruefbedingungen, 273 Fremdschluessel.


alter table public.akq_aktivitaeten add constraint akq_aktivitaeten_pkey PRIMARY KEY (id);
alter table public.akq_automation_lauf add constraint akq_automation_lauf_pkey PRIMARY KEY (id);
alter table public.akq_automationen add constraint akq_automationen_pkey PRIMARY KEY (id);
alter table public.akq_eingang_log add constraint akq_eingang_log_pkey PRIMARY KEY (id);
alter table public.akq_einstellungen add constraint akq_einstellungen_pkey PRIMARY KEY (id);
alter table public.akq_kampagnen add constraint akq_kampagnen_pkey PRIMARY KEY (id);
alter table public.akq_lead_historie add constraint akq_lead_historie_pkey PRIMARY KEY (id);
alter table public.akq_leads add constraint akq_leads_pkey PRIMARY KEY (id);
alter table public.akq_mail_leads add constraint akq_mail_leads_mail_eingang_id_key UNIQUE (mail_eingang_id);
alter table public.akq_mail_leads add constraint akq_mail_leads_pkey PRIMARY KEY (id);
alter table public.akq_mail_regeln add constraint akq_mail_regeln_pkey PRIMARY KEY (id);
alter table public.akq_pipelines add constraint akq_pipelines_pkey PRIMARY KEY (id);
alter table public.akq_quellen add constraint akq_quellen_pkey PRIMARY KEY (id);
alter table public.akq_quellen add constraint akq_quellen_slug_key UNIQUE (slug);
alter table public.akq_stufen add constraint akq_stufen_pkey PRIMARY KEY (id);
alter table public.akq_vorlagen add constraint akq_vorlagen_pkey PRIMARY KEY (id);
alter table public.aktivitaeten add constraint aktivitaeten_pkey PRIMARY KEY (id);
alter table public.aktivitaets_log add constraint aktivitaets_log_pkey PRIMARY KEY (id);
alter table public.amt_adressen add constraint amt_adressen_pkey PRIMARY KEY (id);
alter table public.amt_vorlage add constraint amt_vorlage_pkey PRIMARY KEY (id);
alter table public.amt_zusaetzliche_regionen add constraint amt_zusaetzliche_regionen_amt_id_region_key UNIQUE (amt_id, region);
alter table public.amt_zusaetzliche_regionen add constraint amt_zusaetzliche_regionen_pkey PRIMARY KEY (id);
alter table public.arbeitszeit_modelle add constraint arbeitszeit_modelle_pkey PRIMARY KEY (id);
alter table public.arbeitszeit_stempel add constraint arbeitszeit_stempel_pkey PRIMARY KEY (id);
alter table public.arbeitszeit_tage add constraint arbeitszeit_tage_pkey PRIMARY KEY (id);
alter table public.aufgaben add constraint aufgaben_pkey PRIMARY KEY (id);
alter table public.bewerber_antworten add constraint bewerber_antworten_einladung_id_key UNIQUE (einladung_id);
alter table public.bewerber_antworten add constraint bewerber_antworten_pkey PRIMARY KEY (id);
alter table public.bewerber_einladungen add constraint bewerber_einladungen_pkey PRIMARY KEY (id);
alter table public.bewerber_einladungen add constraint bewerber_einladungen_token_key UNIQUE (token);
alter table public.bewertungen add constraint bewertungen_pkey PRIMARY KEY (id);
alter table public.briefe add constraint briefe_pkey PRIMARY KEY (id);
alter table public.checkliste_items add constraint checkliste_items_pkey PRIMARY KEY (id);
alter table public.checkliste_vorlagen add constraint checkliste_vorlagen_name_key UNIQUE (name);
alter table public.checkliste_vorlagen add constraint checkliste_vorlagen_pkey PRIMARY KEY (id);
alter table public.checkliste_vorlagen_items add constraint checkliste_vorlagen_items_pkey PRIMARY KEY (id);
alter table public.dashboard_gesehen add constraint dashboard_gesehen_pkey PRIMARY KEY (id);
alter table public.dokumente add constraint dokumente_pkey PRIMARY KEY (id);
alter table public.ea_accounts add constraint ea_accounts_email_key UNIQUE (email);
alter table public.ea_accounts add constraint ea_accounts_pkey PRIMARY KEY (id);
alter table public.ea_events add constraint ea_events_pkey PRIMARY KEY (id);
alter table public.ea_orders add constraint ea_orders_order_number_key UNIQUE (order_number);
alter table public.ea_orders add constraint ea_orders_pkey PRIMARY KEY (id);
alter table public.eigentuemer add constraint eigentuemer_pkey PRIMARY KEY (id);
alter table public.eigentuemer add constraint eigentuemer_user_id_key UNIQUE (user_id);
alter table public.eigentuemer_benachrichtigung_queue add constraint eigentuemer_benachrichtigung_queue_pkey PRIMARY KEY (id);
alter table public.eigentuemer_dokumente add constraint eigentuemer_dokumente_pkey PRIMARY KEY (id);
alter table public.eigentuemer_einladungen add constraint eigentuemer_einladungen_pkey PRIMARY KEY (id);
alter table public.eigentuemer_einladungen add constraint eigentuemer_einladungen_token_key UNIQUE (token);
alter table public.eigentuemer_nachrichten add constraint eigentuemer_nachrichten_pkey PRIMARY KEY (id);
alter table public.eigentuemer_objekte add constraint eigentuemer_objekte_eigentuemer_id_maklervertrag_id_key UNIQUE (eigentuemer_id, maklervertrag_id);
alter table public.eigentuemer_objekte add constraint eigentuemer_objekte_pkey PRIMARY KEY (id);
alter table public.eigentuemer_personen add constraint eigentuemer_personen_pkey PRIMARY KEY (id);
alter table public.eigentuemer_personen add constraint eigentuemer_personen_user_id_key UNIQUE (user_id);
alter table public.energieausweis_anfragen add constraint energieausweis_anfragen_pkey PRIMARY KEY (id);
alter table public.expose_debug add constraint expose_debug_pkey PRIMARY KEY (id);
alter table public.expose_entwuerfe add constraint expose_entwuerfe_pkey PRIMARY KEY (id);
alter table public.expose_freigaben add constraint expose_freigaben_pkey PRIMARY KEY (id);
alter table public.expose_freigaben add constraint expose_freigaben_token_key UNIQUE (token);
alter table public.external_credentials add constraint external_credentials_pkey PRIMARY KEY (id);
alter table public.external_credentials add constraint external_credentials_service_key UNIQUE (service);
alter table public.external_credentials_audit add constraint external_credentials_audit_pkey PRIMARY KEY (id);
alter table public.fehler_protokoll add constraint fehler_protokoll_pkey PRIMARY KEY (id);
alter table public.finanzierungs_annahmen add constraint finanzierungs_annahmen_pkey PRIMARY KEY (id);
alter table public.firma_kennzahlen add constraint firma_kennzahlen_jahr_key UNIQUE (jahr);
alter table public.firma_kennzahlen add constraint firma_kennzahlen_pkey PRIMARY KEY (id);
alter table public.firma_stammdaten add constraint firma_stammdaten_pkey PRIMARY KEY (id);
alter table public.firma_stammdaten add constraint firma_stammdaten_slug_key UNIQUE (slug);
alter table public.geo_cache add constraint geo_cache_pkey PRIMARY KEY (adresse_norm);
alter table public.immobilie_datei add constraint immobilie_datei_pkey PRIMARY KEY (id);
alter table public.immobilie_eigentuemer add constraint immobilie_eigentuemer_immobilie_id_eigentuemer_id_key UNIQUE (immobilie_id, eigentuemer_id);
alter table public.immobilie_eigentuemer add constraint immobilie_eigentuemer_pkey PRIMARY KEY (id);
alter table public.immobilie_fahrt_cache add constraint immobilie_fahrt_cache_pkey PRIMARY KEY (immobilie_id);
alter table public.immobilie_grundstueck add constraint immobilie_grundstueck_pkey PRIMARY KEY (immobilie_id);
alter table public.immobilie_kosten_einstellung add constraint immobilie_kosten_einstellung_pkey PRIMARY KEY (immobilie_id);
alter table public.immobilie_kosten_position add constraint immobilie_kosten_position_pkey PRIMARY KEY (id);
alter table public.immobilie_onedrive add constraint immobilie_onedrive_pkey PRIMARY KEY (immobilie_id);
alter table public.immobilie_portal_status add constraint immobilie_portal_status_immobilie_id_portal_key UNIQUE (immobilie_id, portal);
alter table public.immobilie_portal_status add constraint immobilie_portal_status_pkey PRIMARY KEY (id);
alter table public.immobilie_wissen add constraint immobilie_wissen_pkey PRIMARY KEY (id);
alter table public.immobilien add constraint immobilien_pkey PRIMARY KEY (id);
alter table public.jotform_formulare add constraint jotform_formulare_form_id_key UNIQUE (form_id);
alter table public.jotform_formulare add constraint jotform_formulare_pkey PRIMARY KEY (id);
alter table public.ki_bildbearbeitung_log add constraint ki_bildbearbeitung_log_pkey PRIMARY KEY (id);
alter table public.ki_pruefungen add constraint ki_pruefungen_pkey PRIMARY KEY (id);
alter table public.kontakt_objekt add constraint kontakt_objekt_kontakt_id_immobilie_id_rolle_key UNIQUE (kontakt_id, immobilie_id, rolle);
alter table public.kontakt_objekt add constraint kontakt_objekt_pkey PRIMARY KEY (id);
alter table public.kontakte add constraint kontakte_pkey PRIMARY KEY (id);
alter table public.kosten_saetze add constraint kosten_saetze_pkey PRIMARY KEY (id);
alter table public.liquid_imports add constraint liquid_imports_pkey PRIMARY KEY (id);
alter table public.liquid_kategorisierung add constraint liquid_kat_match_unique UNIQUE (match_key);
alter table public.liquid_kategorisierung add constraint liquid_kategorisierung_pkey PRIMARY KEY (id);
alter table public.liquid_konten add constraint liquid_konten_iban_unique UNIQUE (iban);
alter table public.liquid_konten add constraint liquid_konten_pkey PRIMARY KEY (id);
alter table public.liquid_settings add constraint liquid_settings_pkey PRIMARY KEY (id);
alter table public.liquid_szenarien add constraint liquid_szenarien_pkey PRIMARY KEY (id);
alter table public.liquid_transaktionen add constraint liquid_trans_dedup_unique UNIQUE (konto_id, dedup_hash);
alter table public.liquid_transaktionen add constraint liquid_transaktionen_pkey PRIMARY KEY (id);
alter table public.mail_absender_onedrive add constraint mail_absender_onedrive_pkey PRIMARY KEY (id);
alter table public.mail_absender_onedrive add constraint mail_absender_onedrive_user_id_absender_email_key UNIQUE (user_id, absender_email);
alter table public.mail_abwesenheit_log add constraint mail_abwesenheit_log_pkey PRIMARY KEY (id);
alter table public.mail_blockierte_absender add constraint mail_blockierte_absender_benutzer_id_email_key UNIQUE (benutzer_id, email);
alter table public.mail_blockierte_absender add constraint mail_blockierte_absender_pkey PRIMARY KEY (id);
alter table public.mail_eigene_ordner add constraint mail_eigene_ordner_pkey PRIMARY KEY (id);
alter table public.mail_eingang add constraint mail_eingang_pkey PRIMARY KEY (id);
alter table public.mail_kategorien add constraint mail_kategorien_pkey PRIMARY KEY (id);
alter table public.mail_ki_log add constraint mail_ki_log_pkey PRIMARY KEY (id);
alter table public.mail_ordner add constraint mail_ordner_pkey PRIMARY KEY (id);
alter table public.mail_ordner add constraint mail_ordner_postfach_id_name_key UNIQUE (postfach_id, name);
alter table public.mail_postfaecher add constraint mail_postfaecher_benutzer_id_email_adresse_key UNIQUE (benutzer_id, email_adresse);
alter table public.mail_postfaecher add constraint mail_postfaecher_pkey PRIMARY KEY (id);
alter table public.mail_regeln add constraint mail_regeln_pkey PRIMARY KEY (id);
alter table public.mail_versendet add constraint mail_versendet_pkey PRIMARY KEY (id);
alter table public.mail_vorlagen add constraint mail_vorlagen_pkey PRIMARY KEY (id);
alter table public.marketing add constraint marketing_pkey PRIMARY KEY (id);
alter table public.marketing_print_vorlagen add constraint marketing_print_vorlagen_pkey PRIMARY KEY (id);
alter table public.mietanfragen add constraint mietanfragen_jotform_submission_id_key UNIQUE (jotform_submission_id);
alter table public.mietanfragen add constraint mietanfragen_pkey PRIMARY KEY (id);
alter table public.mietvertraege add constraint mietvertraege_pkey PRIMARY KEY (id);
alter table public.mietvertrag_ordner add constraint mietvertrag_ordner_pkey PRIMARY KEY (id);
alter table public.mpe_bausteine add constraint mpe_bausteine_pkey PRIMARY KEY (id);
alter table public.news_briefings add constraint news_briefings_briefing_datum_key UNIQUE (briefing_datum);
alter table public.news_briefings add constraint news_briefings_pkey PRIMARY KEY (id);
alter table public.notar_laufzettel add constraint notar_laufzettel_pkey PRIMARY KEY (id);
alter table public.notiz_tags add constraint notiz_tags_pkey PRIMARY KEY (id);
alter table public.notiz_tags add constraint notiz_tags_user_id_name_key UNIQUE (user_id, name);
alter table public.notizen add constraint notizen_pkey PRIMARY KEY (id);
alter table public.objektaufnahme_fotos add constraint objektaufnahme_fotos_pkey PRIMARY KEY (id);
alter table public.objektaufnahmen add constraint objektaufnahmen_pkey PRIMARY KEY (id);
alter table public.objektnachweise add constraint objektnachweise_pkey PRIMARY KEY (id);
alter table public.onoffice_adressen add constraint onoffice_adressen_pkey PRIMARY KEY (onoffice_id);
alter table public.onoffice_diagnose add constraint onoffice_diagnose_pkey PRIMARY KEY (id);
alter table public.onoffice_export_log add constraint onoffice_export_log_pkey PRIMARY KEY (id);
alter table public.onoffice_feld_werte add constraint onoffice_feld_werte_pkey PRIMARY KEY (feld, oo_key);
alter table public.onoffice_felder add constraint onoffice_felder_pkey PRIMARY KEY (feld);
alter table public.onoffice_import_log add constraint onoffice_import_log_pkey PRIMARY KEY (id);
alter table public.onoffice_objekte add constraint onoffice_objekte_pkey PRIMARY KEY (onoffice_id);
alter table public.onoffice_schreib_felder add constraint onoffice_schreib_felder_pkey PRIMARY KEY (feld);
alter table public.onoffice_sync_log add constraint onoffice_sync_log_pkey PRIMARY KEY (id);
alter table public.plz_region add constraint plz_region_pkey PRIMARY KEY (id);
alter table public.plz_region add constraint plz_region_plz_ort_region_key UNIQUE (plz, ort, region);
alter table public.portal_diagnose add constraint portal_diagnose_pkey PRIMARY KEY (id);
alter table public.portal_zugaenge add constraint portal_zugaenge_pkey PRIMARY KEY (id);
alter table public.portal_zugaenge add constraint portal_zugaenge_portal_key UNIQUE (portal);
alter table public.profiles add constraint profiles_email_key UNIQUE (email);
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.projekt_aktivitaeten add constraint projekt_aktivitaeten_pkey PRIMARY KEY (id);
alter table public.projekt_anfragen add constraint projekt_anfragen_pkey PRIMARY KEY (id);
alter table public.projekt_dateien add constraint projekt_dateien_pkey PRIMARY KEY (id);
alter table public.projekt_einheiten add constraint projekt_einheiten_pkey PRIMARY KEY (id);
alter table public.projekt_einheiten add constraint projekt_einheiten_projekt_id_we_nr_key UNIQUE (projekt_id, we_nr);
alter table public.projekt_kontakte add constraint projekt_kontakte_pkey PRIMARY KEY (id);
alter table public.projekt_kunden_dateien add constraint projekt_kunden_dateien_pkey PRIMARY KEY (id);
alter table public.projekt_maengel add constraint projekt_maengel_pkey PRIMARY KEY (id);
alter table public.projekt_merkliste add constraint projekt_merkliste_pkey PRIMARY KEY (id);
alter table public.projekt_merkliste add constraint projekt_merkliste_zugang_id_einheit_id_key UNIQUE (zugang_id, einheit_id);
alter table public.projekt_nachrichten add constraint projekt_nachrichten_pkey PRIMARY KEY (id);
alter table public.projekt_ordner add constraint projekt_ordner_pkey PRIMARY KEY (id);
alter table public.projekt_updates add constraint projekt_updates_pkey PRIMARY KEY (id);
alter table public.projekt_zahlungsplan add constraint projekt_zahlungsplan_pkey PRIMARY KEY (id);
alter table public.projekt_zugaenge add constraint projekt_zugaenge_pkey PRIMARY KEY (id);
alter table public.projekt_zugaenge add constraint projekt_zugaenge_token_key UNIQUE (token);
alter table public.projekte add constraint projekte_pkey PRIMARY KEY (id);
alter table public.projekte add constraint projekte_slug_key UNIQUE (slug);
alter table public.provision_tracker add constraint provision_tracker_pkey PRIMARY KEY (id);
alter table public.push_einstellungen add constraint push_einstellungen_pkey PRIMARY KEY (id);
alter table public.push_geraete add constraint push_geraete_pkey PRIMARY KEY (id);
alter table public.push_geraete add constraint push_geraete_token_key UNIQUE (token);
alter table public.push_log add constraint push_log_pkey PRIMARY KEY (id);
alter table public.push_termin_erinnerungen add constraint push_termin_erinnerungen_pkey PRIMARY KEY (termin_id, profile_id);
alter table public.radar_aktivitaeten add constraint radar_aktivitaeten_pkey PRIMARY KEY (id);
alter table public.radar_historie add constraint radar_historie_pkey PRIMARY KEY (id);
alter table public.radar_objekte add constraint radar_objekte_pkey PRIMARY KEY (id);
alter table public.radar_suchauftraege add constraint radar_suchauftraege_pkey PRIMARY KEY (id);
alter table public.rechnung_kunden add constraint rechnung_kunden_pkey PRIMARY KEY (id);
alter table public.rechnung_nummern_sequence add constraint rechnung_nummern_sequence_pkey PRIMARY KEY (firma_id, jahr);
alter table public.rechnung_positionen add constraint rechnung_positionen_pkey PRIMARY KEY (id);
alter table public.rechnungen add constraint rechnungen_pkey PRIMARY KEY (id);
alter table public.rechnungen add constraint rechnungen_rechnungsnummer_key UNIQUE (rechnungsnummer);
alter table public.rechnungen_audit add constraint rechnungen_audit_pkey PRIMARY KEY (id);
alter table public.reservierungen_neubau add constraint reservierungen_neubau_pkey PRIMARY KEY (id);
alter table public.rundgaenge add constraint rundgaenge_pkey PRIMARY KEY (id);
alter table public.rundgaenge add constraint rundgaenge_share_token_key UNIQUE (share_token);
alter table public.rundgang_hotspots add constraint rundgang_hotspots_pkey PRIMARY KEY (id);
alter table public.rundgang_szenen add constraint rundgang_szenen_pkey PRIMARY KEY (id);
alter table public.signatur_empfaenger add constraint signatur_empfaenger_pkey PRIMARY KEY (id);
alter table public.signatur_empfaenger add constraint signatur_empfaenger_token_key UNIQUE (token);
alter table public.signatur_events add constraint signatur_events_pkey PRIMARY KEY (id);
alter table public.signatur_vorgaenge add constraint signatur_vorgaenge_pkey PRIMARY KEY (id);
alter table public.suchkriterien_lauf add constraint suchkriterien_lauf_pkey PRIMARY KEY (id);
alter table public.suchkriterien_treffer add constraint suchkriterien_treffer_pkey PRIMARY KEY (kontakt_id, immobilie_id);
alter table public.termin_einladungen add constraint termin_einladungen_pkey PRIMARY KEY (id);
alter table public.termin_einladungen add constraint termin_einladungen_termin_id_email_key UNIQUE (termin_id, email);
alter table public.termine add constraint termine_pkey PRIMARY KEY (id);
alter table public.todo_kommentar add constraint todo_kommentar_pkey PRIMARY KEY (id);
alter table public.todo_schritt add constraint todo_schritt_pkey PRIMARY KEY (id);
alter table public.todo_verknuepfung add constraint todo_verknuepfung_pkey PRIMARY KEY (id);
alter table public.todo_verknuepfung add constraint todo_verknuepfung_todo_id_objekt_typ_objekt_id_key UNIQUE (todo_id, objekt_typ, objekt_id);
alter table public.todo_vorgang add constraint todo_vorgang_pkey PRIMARY KEY (id);
alter table public.todo_vorlage add constraint todo_vorlage_pkey PRIMARY KEY (id);
alter table public.todo_vorlage_schritt add constraint todo_vorlage_schritt_pkey PRIMARY KEY (id);
alter table public.todo_vorlage_schritt add constraint todo_vorlage_schritt_vorlage_id_nr_key UNIQUE (vorlage_id, nr);
alter table public.todos add constraint todos_pkey PRIMARY KEY (id);
alter table public.uebergabeprotokoll add constraint uebergabeprotokoll_pkey PRIMARY KEY (id);
alter table public.upload_benachrichtigungen add constraint upload_benachrichtigungen_pkey PRIMARY KEY (id);
alter table public.urlaub_hinweise add constraint urlaub_hinweise_pkey PRIMARY KEY (id);
alter table public.verbrauchsausweis_antraege add constraint verbrauchsausweis_antraege_pkey PRIMARY KEY (id);
alter table public.vermerke add constraint vermerke_pkey PRIMARY KEY (id);
alter table public.vertraege add constraint vertraege_pkey PRIMARY KEY (id);
alter table public.waechter_status add constraint waechter_status_pkey PRIMARY KEY (id);
alter table public.web_leads add constraint web_leads_pkey PRIMARY KEY (id);
alter table public.akq_aktivitaeten add constraint akq_aktivitaeten_prioritaet_check CHECK ((prioritaet = ANY (ARRAY['niedrig'::text, 'normal'::text, 'hoch'::text])));
alter table public.akq_aktivitaeten add constraint akq_aktivitaeten_typ_check CHECK ((typ = ANY (ARRAY['anruf'::text, 'termin'::text, 'aufgabe'::text, 'mail'::text, 'whatsapp'::text, 'ki'::text])));
alter table public.akq_automation_lauf add constraint akq_automation_lauf_status_check CHECK ((status = ANY (ARRAY['geplant'::text, 'erledigt'::text, 'abgebrochen'::text, 'fehler'::text])));
alter table public.akq_automationen add constraint akq_automationen_kanal_check CHECK ((kanal = ANY (ARRAY['mail'::text, 'whatsapp'::text, 'aufgabe'::text, 'vorschlag'::text])));
alter table public.akq_einstellungen add constraint akq_einstellungen_id_check CHECK (id);
alter table public.akq_leads add constraint akq_leads_status_check CHECK ((status = ANY (ARRAY['offen'::text, 'gewonnen'::text, 'verloren'::text])));
alter table public.akq_mail_leads add constraint akq_mail_leads_status_check CHECK ((status = ANY (ARRAY['offen'::text, 'uebernommen'::text, 'verworfen'::text, 'kein_lead'::text])));
alter table public.akq_pipelines add constraint akq_pipelines_art_check CHECK ((art = ANY (ARRAY['setting'::text, 'closing'::text, 'wunschimmo'::text])));
alter table public.akq_quellen add constraint akq_quellen_art_check CHECK ((art = ANY (ARRAY['online'::text, 'offline'::text, 'netzwerk'::text, 'tippgeber'::text])));
alter table public.akq_vorlagen add constraint akq_vorlagen_kanal_check CHECK ((kanal = ANY (ARRAY['mail'::text, 'whatsapp'::text, 'aufgabe'::text])));
alter table public.aktivitaeten add constraint aktivitaeten_zielgruppe_check CHECK ((zielgruppe = ANY (ARRAY['makler'::text, 'eigentuemer'::text, 'beide'::text])));
alter table public.amt_adressen add constraint amt_adressen_unterlagentyp_check CHECK ((unterlagentyp = ANY (ARRAY['grundbuch'::text, 'flurkarte'::text, 'baulasten'::text, 'altlasten'::text])));
alter table public.amt_vorlage add constraint amt_vorlage_unterlagentyp_check CHECK ((unterlagentyp = ANY (ARRAY['grundbuch'::text, 'flurkarte'::text, 'baulasten'::text, 'altlasten'::text])));
alter table public.amt_vorlage add constraint amt_vorlage_vorlage_typ_check CHECK ((vorlage_typ = ANY (ARRAY['email'::text, 'brief'::text])));
alter table public.arbeitszeit_stempel add constraint arbeitszeit_stempel_richtung_check CHECK ((richtung = ANY (ARRAY['kommen'::text, 'gehen'::text])));
alter table public.arbeitszeit_tage add constraint arbeitszeit_tage_art_check CHECK ((art = ANY (ARRAY['arbeit'::text, 'urlaub'::text, 'krank'::text, 'feiertag'::text, 'geschenk'::text, 'ausgleich'::text, 'frei'::text, 'sonstige'::text])));
alter table public.bewerber_antworten add constraint bewerber_antworten_empfehlung_check CHECK ((empfehlung = ANY (ARRAY['sehr_gut'::text, 'gespraech'::text, 'kein_match'::text])));
alter table public.bewerber_einladungen add constraint bewerber_einladungen_status_check CHECK ((status = ANY (ARRAY['offen'::text, 'gestartet'::text, 'abgeschlossen'::text, 'widerrufen'::text])));
alter table public.checkliste_items add constraint checkliste_items_anfrage_status_check CHECK ((anfrage_status = ANY (ARRAY['nicht_angefragt'::text, 'beantragt'::text, 'erhalten'::text, 'nicht_noetig'::text])));
alter table public.checkliste_items add constraint checkliste_items_status_check CHECK ((status = ANY (ARRAY['offen'::text, 'erledigt'::text, 'nicht_erforderlich'::text])));
alter table public.checkliste_items add constraint checkliste_items_unterlagentyp_check CHECK ((unterlagentyp = ANY (ARRAY['grundbuch'::text, 'flurkarte'::text, 'baulasten'::text, 'altlasten'::text])));
alter table public.checkliste_vorlagen add constraint checkliste_vorlagen_vertragsart_check CHECK ((vertragsart = ANY (ARRAY['verkauf'::text, 'vermietung'::text, 'beides'::text])));
alter table public.eigentuemer add constraint eigentuemer_portal_typ_chk CHECK (((portal_typ IS NULL) OR (portal_typ = ANY (ARRAY['eigentuemer'::text, 'kaeufer'::text]))));
alter table public.eigentuemer_dokumente add constraint eigentuemer_dokumente_freigabe_check CHECK ((freigabe_status = ANY (ARRAY['nicht_relevant'::text, 'wartet_freigabe'::text, 'entwurf'::text, 'mit_anmerkungen'::text, 'freigegeben'::text])));
alter table public.eigentuemer_dokumente add constraint eigentuemer_dokumente_hochgeladen_von_typ_check CHECK ((hochgeladen_von_typ = ANY (ARRAY['eigentuemer'::text, 'makler'::text])));
alter table public.eigentuemer_dokumente add constraint eigentuemer_dokumente_kategorie_check CHECK ((kategorie = ANY (ARRAY['grundbuch'::text, 'energieausweis'::text, 'teilungserklaerung'::text, 'baulasten'::text, 'altlasten'::text, 'versicherung'::text, 'mieterliste'::text, 'lageplan'::text, 'wartung'::text, 'sonstiges'::text, 'wohnflaechenberechnung'::text, 'grundrisse'::text, 'flurkarte'::text, 'vollmacht'::text, 'grundsteuer'::text, 'nebenkostenabrechnung'::text, 'baubeschreibung'::text, 'bauantrag'::text, 'umbauter_raum'::text, 'mietvertrag'::text, 'gutachten'::text, 'anliegerbeitrag'::text, 'veraenderungsvorschlaege'::text, 'expose'::text, 'einwertung'::text, 'maklervertrag_kopie'::text, 'provisionsrechnung'::text, 'uebergabeprotokoll'::text, 'notar_laufzettel'::text, 'makler_sonstiges'::text, 'verbrauchsausweis'::text])));
alter table public.eigentuemer_einladungen add constraint eigentuemer_einladungen_status_check CHECK ((status = ANY (ARRAY['offen'::text, 'angenommen'::text, 'abgelaufen'::text, 'widerrufen'::text])));
alter table public.eigentuemer_nachrichten add constraint eigentuemer_nachrichten_absender_typ_check CHECK ((absender_typ = ANY (ARRAY['makler'::text, 'eigentuemer'::text])));
alter table public.fehler_protokoll add constraint fehler_protokoll_status_check CHECK ((status = ANY (ARRAY['offen'::text, 'erledigt'::text])));
alter table public.immobilie_datei add constraint immobilie_datei_speicher_typ_check CHECK ((speicher_typ = ANY (ARRAY['supabase'::text, 'onedrive'::text, 'extern'::text])));
alter table public.immobilie_kosten_position add constraint immobilie_kosten_position_quelle_check CHECK ((quelle = ANY (ARRAY['auto'::text, 'manuell'::text])));
alter table public.immobilie_kosten_position add constraint immobilie_kosten_position_typ_check CHECK ((typ = ANY (ARRAY['termin'::text, 'fahrt'::text, 'telefon'::text, 'korrespondenz'::text, 'aufbereitung'::text, 'bilder'::text, 'expose'::text, 'energieausweis'::text, 'portal'::text, 'werbung'::text, 'fremdkosten'::text, 'sonstiges'::text])));
alter table public.immobilien add constraint immobilien_status_check CHECK ((status = ANY (ARRAY['akquise'::text, 'vorbereitung'::text, 'vermarktung'::text, 'reserviert'::text, 'verkauft'::text, 'vermietet'::text, 'archiviert'::text])));
alter table public.immobilien add constraint immobilien_vertragsart_check CHECK ((vertragsart = ANY (ARRAY['verkauf'::text, 'vermietung'::text, 'beides'::text])));
alter table public.ki_pruefungen add constraint ki_pruefungen_ampel_check CHECK ((ampel = ANY (ARRAY['gruen'::text, 'gelb'::text, 'rot'::text])));
alter table public.ki_pruefungen add constraint ki_pruefungen_gesamturteil_check CHECK ((gesamturteil = ANY (ARRAY['versandfertig'::text, 'kleine_maengel'::text, 'nicht_versandfertig'::text])));
alter table public.ki_pruefungen add constraint ki_pruefungen_status_check CHECK ((status = ANY (ARRAY['laeuft'::text, 'fertig'::text, 'fehler'::text])));
alter table public.ki_pruefungen add constraint ki_pruefungen_typ_check CHECK ((typ = ANY (ARRAY['expose'::text, 'mietvertrag'::text])));
alter table public.kontakte add constraint kontakte_hat_namen CHECK (((COALESCE(btrim(nachname), ''::text) <> ''::text) OR (COALESCE(btrim(firma), ''::text) <> ''::text)));
alter table public.kosten_saetze add constraint kosten_saetze_id_check CHECK ((id = 1));
alter table public.kosten_saetze add constraint kosten_saetze_telefon_modus_check CHECK ((telefon_modus = ANY (ARRAY['minuten'::text, 'pauschale_je_anruf'::text, 'pauschale_je_objekt_monat'::text])));
alter table public.liquid_settings add constraint single_row CHECK ((id = 1));
alter table public.mail_eingang add constraint mail_eingang_anhaenge_status_check CHECK ((anhaenge_status = ANY (ARRAY['unbekannt'::text, 'extrahiert'::text, 'fehler'::text, 'keine_anhaenge'::text])));
alter table public.mail_eingang add constraint mail_eingang_ordner_check CHECK (((ordner = ANY (ARRAY['posteingang'::text, 'gesendet'::text, 'entwuerfe'::text, 'archiv'::text, 'spam'::text, 'papierkorb'::text])) OR (ordner ~~ 'eo:%'::text)));
alter table public.mail_ordner add constraint mail_ordner_typ_check CHECK ((typ = ANY (ARRAY['inbox'::text, 'sent'::text, 'drafts'::text, 'trash'::text, 'junk'::text, 'archive'::text, 'custom'::text])));
alter table public.mail_postfaecher add constraint mail_postfaecher_imap_security_check CHECK ((imap_security = ANY (ARRAY['ssl'::text, 'starttls'::text, 'none'::text])));
alter table public.mail_postfaecher add constraint mail_postfaecher_smtp_security_check CHECK ((smtp_security = ANY (ARRAY['starttls'::text, 'ssl'::text, 'none'::text])));
alter table public.mail_versendet add constraint mail_versendet_status_check CHECK ((status = ANY (ARRAY['gesendet'::text, 'fehler'::text])));
alter table public.marketing_print_vorlagen add constraint marketing_print_vorlagen_kategorie_check CHECK ((kategorie = ANY (ARRAY['visitenkarte'::text, 'flyer'::text, 'briefpapier'::text, 'rollup'::text, 'aufkleber'::text, 'schild'::text, 'sonstiges'::text])));
alter table public.mietanfragen add constraint mietanfragen_status_check CHECK ((status = ANY (ARRAY['neu'::text, 'in_pruefung'::text, 'besichtigung_geplant'::text, 'besichtigung_erfolgt'::text, 'unterlagen_angefordert'::text, 'zusage'::text, 'absage'::text, 'warteliste'::text, 'vertrag_unterzeichnet'::text, 'archiviert'::text])));
alter table public.mpe_bausteine add constraint mpe_bausteine_layout_check CHECK ((layout = ANY (ARRAY['bild'::text, 'text'::text, 'bild-text'::text])));
alter table public.notar_laufzettel add constraint notar_laufzettel_status_check CHECK ((status = ANY (ARRAY['entwurf'::text, 'bereit'::text, 'versendet'::text, 'abgeschlossen'::text])));
alter table public.notizen add constraint notizen_prio_check CHECK ((prio = ANY (ARRAY['normal'::text, 'wichtig'::text, 'dringend'::text])));
alter table public.notizen add constraint notizen_quelle_check CHECK ((quelle = ANY (ARRAY['text'::text, 'sprache'::text])));
alter table public.notizen add constraint notizen_verknuepft_typ_check CHECK (((verknuepft_typ = ANY (ARRAY['mietanfrage'::text, 'objekt'::text, 'bewertung'::text, 'eigentuemer'::text, 'mail'::text])) OR (verknuepft_typ IS NULL)));
alter table public.notizen add constraint notizen_wiederholung_check CHECK (((wiederholung = ANY (ARRAY['taeglich'::text, 'woechentlich'::text, 'monatlich'::text, 'jaehrlich'::text])) OR (wiederholung IS NULL)));
alter table public.objektaufnahmen add constraint objektaufnahmen_status_check CHECK ((status = ANY (ARRAY['in_arbeit'::text, 'abgeschlossen'::text, 'archiviert'::text])));
alter table public.profiles add constraint profiles_role_check CHECK ((role = ANY (ARRAY['chef'::text, 'mitarbeiter'::text, 'eigentuemer'::text])));
alter table public.profiles add constraint profiles_stufe_check CHECK (((stufe IS NULL) OR (stufe = ANY (ARRAY['chef'::text, 'standortleitung'::text, 'makler'::text, 'assistenz'::text]))));
alter table public.projekt_dateien add constraint projekt_dateien_sichtbarkeit_check CHECK ((sichtbarkeit = ANY (ARRAY['oeffentlich'::text, 'interessent'::text, 'kaeufer'::text])));
alter table public.projekt_einheiten add constraint projekt_einheiten_status_check CHECK ((status = ANY (ARRAY['verfuegbar'::text, 'reserviert'::text, 'verkauft'::text, 'vermietet'::text])));
alter table public.projekt_nachrichten add constraint projekt_nachrichten_richtung_check CHECK ((richtung = ANY (ARRAY['kunde'::text, 'makler'::text])));
alter table public.projekt_updates add constraint projekt_updates_sichtbarkeit_check CHECK ((sichtbarkeit = ANY (ARRAY['oeffentlich'::text, 'interessent'::text, 'kaeufer'::text])));
alter table public.projekt_zugaenge add constraint projekt_zugaenge_rolle_check CHECK ((rolle = ANY (ARRAY['interessent'::text, 'reserviert'::text, 'kaeufer'::text])));
alter table public.projekte add constraint projekte_status_check CHECK ((status = ANY (ARRAY['entwurf'::text, 'aktiv'::text, 'archiviert'::text])));
alter table public.projekte add constraint projekte_vermarktungsart_check CHECK ((vermarktungsart = ANY (ARRAY['kauf'::text, 'miete'::text])));
alter table public.push_einstellungen add constraint push_einstellungen_id_check CHECK ((id = 1));
alter table public.push_geraete add constraint push_geraete_plattform_check CHECK ((plattform = 'ios'::text));
alter table public.rechnungen add constraint rechnungen_rechnung_typ_check CHECK ((rechnung_typ = ANY (ARRAY['frei'::text, 'verkaeufer_provision'::text, 'kaeufer_provision'::text])));
alter table public.rechnungen add constraint rechnungen_rechnungstyp_check CHECK ((rechnungstyp = ANY (ARRAY['frei'::text, 'verkaeufer_provision'::text, 'kaeufer_provision'::text])));
alter table public.rechnungen add constraint rechnungen_status_check CHECK ((status = ANY (ARRAY['entwurf'::text, 'gestellt'::text, 'storniert'::text, 'storno_rechnung'::text, 'bezahlt'::text])));
alter table public.rundgaenge add constraint rundgaenge_status_check CHECK ((status = ANY (ARRAY['entwurf'::text, 'oeffentlich'::text, 'archiv'::text])));
alter table public.rundgang_hotspots add constraint rundgang_hotspots_typ_check CHECK ((typ = ANY (ARRAY['szene'::text, 'info'::text])));
alter table public.signatur_empfaenger add constraint signatur_empfaenger_rolle_check CHECK ((rolle = ANY (ARRAY['eigentuemer'::text, 'makler'::text, 'kaeufer'::text])));
alter table public.signatur_empfaenger add constraint signatur_empfaenger_status_check CHECK ((status = ANY (ARRAY['wartend'::text, 'eingeladen'::text, 'geoeffnet'::text, 'unterschrieben'::text, 'abgelehnt'::text])));
alter table public.signatur_events add constraint signatur_events_event_typ_check CHECK ((event_typ = ANY (ARRAY['vorgang_erstellt'::text, 'mail_gesendet'::text, 'mail_fehlgeschlagen'::text, 'link_geoeffnet'::text, 'unterschrieben'::text, 'abgelehnt'::text, 'abgelaufen'::text, 'widerrufen'::text, 'abgeschlossen'::text])));
alter table public.signatur_vorgaenge add constraint signatur_vorgaenge_dokument_typ_check CHECK ((dokument_typ = ANY (ARRAY['maklervertrag'::text, 'vollmacht'::text, 'objektnachweis'::text, 'reservierung'::text])));
alter table public.signatur_vorgaenge add constraint signatur_vorgaenge_status_check CHECK ((status = ANY (ARRAY['offen'::text, 'wartet_kaeufer'::text, 'wartet_eigentuemer'::text, 'wartet_makler'::text, 'abgeschlossen'::text, 'abgelaufen'::text, 'widerrufen'::text])));
alter table public.suchkriterien_lauf add constraint suchkriterien_lauf_id_check CHECK ((id = 1));
alter table public.termine add constraint termine_fahrt_richtung_check CHECK ((fahrt_richtung = ANY (ARRAY['hin'::text, 'rueck'::text])));
alter table public.todo_verknuepfung add constraint todo_verknuepfung_objekt_typ_check CHECK ((objekt_typ = ANY (ARRAY['immobilie'::text, 'kontakt'::text, 'vertrag'::text, 'mail_eingang'::text, 'termin'::text, 'rechnung'::text, 'bewertung'::text, 'eigentuemer'::text, 'objektnachweis'::text, 'mietanfrage'::text, 'akq_lead'::text])));
alter table public.todo_vorgang add constraint todo_vorgang_status_check CHECK ((status = ANY (ARRAY['laeuft'::text, 'fertig'::text, 'abgebrochen'::text])));
alter table public.todo_vorlage_schritt add constraint todo_vorlage_schritt_offset_ab_check CHECK ((offset_ab = ANY (ARRAY['start'::text, 'vorgaenger'::text])));
alter table public.todos add constraint todos_prioritaet_check CHECK ((prioritaet = ANY (ARRAY['normal'::text, 'wichtig'::text, 'dringend'::text])));
alter table public.todos add constraint todos_status_check CHECK ((status = ANY (ARRAY['offen'::text, 'laeuft'::text, 'wartet'::text, 'erledigt'::text, 'verworfen'::text])));
alter table public.uebergabeprotokoll add constraint uebergabeprotokoll_kontext_check CHECK ((kontext = ANY (ARRAY['vermietung'::text, 'verkauf'::text])));
alter table public.uebergabeprotokoll add constraint uebergabeprotokoll_protokoll_typ_check CHECK ((protokoll_typ = ANY (ARRAY['einzug'::text, 'auszug'::text])));
alter table public.uebergabeprotokoll add constraint uebergabeprotokoll_rauchmelder_typ_check CHECK ((rauchmelder_typ = ANY (ARRAY['vermieter'::text, 'mieter'::text, 'keine'::text])));
alter table public.uebergabeprotokoll add constraint uebergabeprotokoll_status_check CHECK ((status = ANY (ARRAY['entwurf'::text, 'abgeschlossen'::text])));
alter table public.verbrauchsausweis_antraege add constraint verbrauchsausweis_antraege_erstellt_von_typ_check CHECK ((erstellt_von_typ = ANY (ARRAY['eigentuemer'::text, 'makler'::text])));
alter table public.verbrauchsausweis_antraege add constraint verbrauchsausweis_antraege_status_check CHECK ((status = ANY (ARRAY['in_arbeit'::text, 'eingereicht'::text, 'in_bearbeitung'::text, 'abgeschlossen'::text, 'archiviert'::text])));
alter table public.vermerke add constraint vermerke_dauer_check CHECK (((dauer_minuten IS NULL) OR ((dauer_minuten >= 0) AND (dauer_minuten <= 1440))));
alter table public.vermerke add constraint vermerke_quelle_check CHECK (((quelle IS NULL) OR (quelle = ANY (ARRAY['klick'::text, 'manuell'::text, 'sipgate'::text]))));
alter table public.vermerke add constraint vermerke_richtung_check CHECK (((richtung IS NULL) OR (richtung = ANY (ARRAY['ausgehend'::text, 'eingehend'::text]))));
alter table public.akq_aktivitaeten add constraint akq_aktivitaeten_automation_id_fkey FOREIGN KEY (automation_id) REFERENCES akq_automationen(id) ON DELETE SET NULL;
alter table public.akq_aktivitaeten add constraint akq_aktivitaeten_erstellt_von_fkey FOREIGN KEY (erstellt_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.akq_aktivitaeten add constraint akq_aktivitaeten_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES akq_leads(id) ON DELETE CASCADE;
alter table public.akq_aktivitaeten add constraint akq_aktivitaeten_termin_id_fkey FOREIGN KEY (termin_id) REFERENCES termine(id) ON DELETE SET NULL;
alter table public.akq_aktivitaeten add constraint akq_aktivitaeten_zustaendig_id_fkey FOREIGN KEY (zustaendig_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.akq_automation_lauf add constraint akq_automation_lauf_automation_id_fkey FOREIGN KEY (automation_id) REFERENCES akq_automationen(id) ON DELETE SET NULL;
alter table public.akq_automation_lauf add constraint akq_automation_lauf_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES akq_leads(id) ON DELETE CASCADE;
alter table public.akq_automationen add constraint akq_automationen_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES akq_pipelines(id) ON DELETE CASCADE;
alter table public.akq_automationen add constraint akq_automationen_quelle_id_fkey FOREIGN KEY (quelle_id) REFERENCES akq_quellen(id) ON DELETE CASCADE;
alter table public.akq_automationen add constraint akq_automationen_stufe_id_fkey FOREIGN KEY (stufe_id) REFERENCES akq_stufen(id) ON DELETE CASCADE;
alter table public.akq_automationen add constraint akq_automationen_vorlage_id_fkey FOREIGN KEY (vorlage_id) REFERENCES akq_vorlagen(id) ON DELETE SET NULL;
alter table public.akq_lead_historie add constraint akq_lead_historie_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES akq_leads(id) ON DELETE CASCADE;
alter table public.akq_lead_historie add constraint akq_lead_historie_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.akq_leads add constraint akq_leads_bewertung_id_fkey FOREIGN KEY (bewertung_id) REFERENCES bewertungen(id) ON DELETE SET NULL;
alter table public.akq_leads add constraint akq_leads_erstellt_von_fkey FOREIGN KEY (erstellt_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.akq_leads add constraint akq_leads_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.akq_leads add constraint akq_leads_kontakt_id_fkey FOREIGN KEY (kontakt_id) REFERENCES kontakte(id) ON DELETE SET NULL;
alter table public.akq_leads add constraint akq_leads_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES akq_pipelines(id) ON DELETE SET NULL;
alter table public.akq_leads add constraint akq_leads_quelle_id_fkey FOREIGN KEY (quelle_id) REFERENCES akq_quellen(id) ON DELETE SET NULL;
alter table public.akq_leads add constraint akq_leads_radar_objekt_id_fkey FOREIGN KEY (radar_objekt_id) REFERENCES radar_objekte(id) ON DELETE SET NULL;
alter table public.akq_leads add constraint akq_leads_stufe_id_fkey FOREIGN KEY (stufe_id) REFERENCES akq_stufen(id) ON DELETE SET NULL;
alter table public.akq_leads add constraint akq_leads_tippgeber_kontakt_id_fkey FOREIGN KEY (tippgeber_kontakt_id) REFERENCES kontakte(id) ON DELETE SET NULL;
alter table public.akq_leads add constraint akq_leads_zustaendig_id_fkey FOREIGN KEY (zustaendig_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.akq_mail_leads add constraint akq_mail_leads_bearbeitet_von_fkey FOREIGN KEY (bearbeitet_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.akq_mail_leads add constraint akq_mail_leads_dublette_kontakt_id_fkey FOREIGN KEY (dublette_kontakt_id) REFERENCES kontakte(id) ON DELETE SET NULL;
alter table public.akq_mail_leads add constraint akq_mail_leads_dublette_lead_id_fkey FOREIGN KEY (dublette_lead_id) REFERENCES akq_leads(id) ON DELETE SET NULL;
alter table public.akq_mail_leads add constraint akq_mail_leads_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES akq_leads(id) ON DELETE SET NULL;
alter table public.akq_mail_leads add constraint akq_mail_leads_mail_eingang_id_fkey FOREIGN KEY (mail_eingang_id) REFERENCES mail_eingang(id) ON DELETE CASCADE;
alter table public.akq_mail_leads add constraint akq_mail_leads_quelle_id_fkey FOREIGN KEY (quelle_id) REFERENCES akq_quellen(id) ON DELETE SET NULL;
alter table public.akq_mail_leads add constraint akq_mail_leads_regel_id_fkey FOREIGN KEY (regel_id) REFERENCES akq_mail_regeln(id) ON DELETE SET NULL;
alter table public.akq_mail_regeln add constraint akq_mail_regeln_quelle_id_fkey FOREIGN KEY (quelle_id) REFERENCES akq_quellen(id) ON DELETE SET NULL;
alter table public.akq_pipelines add constraint akq_pipelines_verknuepfte_pipeline_id_fkey FOREIGN KEY (verknuepfte_pipeline_id) REFERENCES akq_pipelines(id) ON DELETE SET NULL;
alter table public.akq_quellen add constraint akq_quellen_kampagne_id_fkey FOREIGN KEY (kampagne_id) REFERENCES akq_kampagnen(id) ON DELETE SET NULL;
alter table public.akq_stufen add constraint akq_stufen_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES akq_pipelines(id) ON DELETE CASCADE;
alter table public.aktivitaeten add constraint aktivitaeten_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE CASCADE;
alter table public.aktivitaeten add constraint aktivitaeten_empfaenger_user_id_fkey FOREIGN KEY (empfaenger_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.aktivitaeten add constraint aktivitaeten_gelesen_von_user_id_fkey FOREIGN KEY (gelesen_von_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.aktivitaeten add constraint aktivitaeten_maklervertrag_id_fkey FOREIGN KEY (maklervertrag_id) REFERENCES vertraege(id) ON DELETE CASCADE;
alter table public.aktivitaets_log add constraint aktivitaets_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.amt_zusaetzliche_regionen add constraint amt_zusaetzliche_regionen_amt_id_fkey FOREIGN KEY (amt_id) REFERENCES amt_adressen(id) ON DELETE CASCADE;
alter table public.arbeitszeit_modelle add constraint arbeitszeit_modelle_profil_id_fkey FOREIGN KEY (profil_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.arbeitszeit_stempel add constraint arbeitszeit_stempel_profil_id_fkey FOREIGN KEY (profil_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.arbeitszeit_tage add constraint arbeitszeit_tage_erfasst_von_fkey FOREIGN KEY (erfasst_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.arbeitszeit_tage add constraint arbeitszeit_tage_profil_id_fkey FOREIGN KEY (profil_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.aufgaben add constraint aufgaben_erledigt_von_fkey FOREIGN KEY (erledigt_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.aufgaben add constraint aufgaben_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.aufgaben add constraint aufgaben_kontakt_id_fkey FOREIGN KEY (kontakt_id) REFERENCES kontakte(id) ON DELETE SET NULL;
alter table public.aufgaben add constraint aufgaben_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES akq_leads(id) ON DELETE CASCADE;
alter table public.aufgaben add constraint aufgaben_termin_id_fkey FOREIGN KEY (termin_id) REFERENCES termine(id) ON DELETE SET NULL;
alter table public.aufgaben add constraint aufgaben_zustaendig_id_fkey FOREIGN KEY (zustaendig_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.bewerber_antworten add constraint bewerber_antworten_einladung_id_fkey FOREIGN KEY (einladung_id) REFERENCES bewerber_einladungen(id) ON DELETE CASCADE;
alter table public.bewerber_einladungen add constraint bewerber_einladungen_erstellt_von_fkey FOREIGN KEY (erstellt_von) REFERENCES profiles(id);
alter table public.bewertungen add constraint bewertungen_akq_lead_id_fkey FOREIGN KEY (akq_lead_id) REFERENCES akq_leads(id) ON DELETE SET NULL;
alter table public.bewertungen add constraint bewertungen_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id);
alter table public.bewertungen add constraint bewertungen_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.briefe add constraint briefe_absender_firma_id_fkey FOREIGN KEY (absender_firma_id) REFERENCES firma_stammdaten(id);
alter table public.checkliste_items add constraint checkliste_items_anfrage_behoerde_id_fkey FOREIGN KEY (anfrage_behoerde_id) REFERENCES amt_adressen(id) ON DELETE SET NULL;
alter table public.checkliste_items add constraint checkliste_items_maklervertrag_id_fkey FOREIGN KEY (maklervertrag_id) REFERENCES vertraege(id) ON DELETE CASCADE;
alter table public.checkliste_vorlagen_items add constraint checkliste_vorlagen_items_vorlage_id_fkey FOREIGN KEY (vorlage_id) REFERENCES checkliste_vorlagen(id) ON DELETE CASCADE;
alter table public.dashboard_gesehen add constraint dashboard_gesehen_benutzer_id_fkey FOREIGN KEY (benutzer_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.dokumente add constraint dokumente_uploader_id_fkey FOREIGN KEY (uploader_id) REFERENCES profiles(id);
alter table public.eigentuemer add constraint eigentuemer_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.eigentuemer add constraint eigentuemer_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.eigentuemer_benachrichtigung_queue add constraint eigentuemer_benachrichtigung_queue_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE CASCADE;
alter table public.eigentuemer_dokumente add constraint eigentuemer_dokumente_antwort_auf_dokument_id_fkey FOREIGN KEY (antwort_auf_dokument_id) REFERENCES eigentuemer_dokumente(id) ON DELETE SET NULL;
alter table public.eigentuemer_dokumente add constraint eigentuemer_dokumente_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE CASCADE;
alter table public.eigentuemer_dokumente add constraint eigentuemer_dokumente_hochgeladen_von_user_id_fkey FOREIGN KEY (hochgeladen_von_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.eigentuemer_dokumente add constraint eigentuemer_dokumente_maklervertrag_id_fkey FOREIGN KEY (maklervertrag_id) REFERENCES vertraege(id) ON DELETE SET NULL;
alter table public.eigentuemer_einladungen add constraint eigentuemer_einladungen_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.eigentuemer_einladungen add constraint eigentuemer_einladungen_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE SET NULL;
alter table public.eigentuemer_einladungen add constraint eigentuemer_einladungen_maklervertrag_id_fkey FOREIGN KEY (maklervertrag_id) REFERENCES vertraege(id) ON DELETE SET NULL;
alter table public.eigentuemer_nachrichten add constraint eigentuemer_nachrichten_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE CASCADE;
alter table public.eigentuemer_objekte add constraint eigentuemer_objekte_ansprechpartner_id_fkey FOREIGN KEY (ansprechpartner_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.eigentuemer_objekte add constraint eigentuemer_objekte_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.eigentuemer_objekte add constraint eigentuemer_objekte_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE CASCADE;
alter table public.eigentuemer_objekte add constraint eigentuemer_objekte_maklervertrag_id_fkey FOREIGN KEY (maklervertrag_id) REFERENCES vertraege(id) ON DELETE CASCADE;
alter table public.eigentuemer_personen add constraint eigentuemer_personen_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.eigentuemer_personen add constraint eigentuemer_personen_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE CASCADE;
alter table public.eigentuemer_personen add constraint eigentuemer_personen_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.expose_entwuerfe add constraint expose_entwuerfe_eigentuemer_wunsch_von_dokument_id_fkey FOREIGN KEY (eigentuemer_wunsch_von_dokument_id) REFERENCES eigentuemer_dokumente(id) ON DELETE SET NULL;
alter table public.expose_entwuerfe add constraint expose_entwuerfe_maklervertrag_id_fkey FOREIGN KEY (maklervertrag_id) REFERENCES vertraege(id) ON DELETE SET NULL;
alter table public.expose_entwuerfe add constraint expose_entwuerfe_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.expose_freigaben add constraint expose_freigaben_erstellt_von_fkey FOREIGN KEY (erstellt_von) REFERENCES auth.users(id);
alter table public.expose_freigaben add constraint expose_freigaben_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.external_credentials add constraint external_credentials_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id);
alter table public.external_credentials_audit add constraint external_credentials_audit_credential_id_fkey FOREIGN KEY (credential_id) REFERENCES external_credentials(id) ON DELETE CASCADE;
alter table public.external_credentials_audit add constraint external_credentials_audit_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
alter table public.fehler_protokoll add constraint fehler_protokoll_benutzer_id_fkey FOREIGN KEY (benutzer_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.firma_stammdaten add constraint firma_stammdaten_inhaber_user_id_fkey FOREIGN KEY (inhaber_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.immobilie_datei add constraint immobilie_datei_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.immobilie_datei add constraint immobilie_datei_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.immobilie_datei add constraint immobilie_datei_mail_eingang_id_fkey FOREIGN KEY (mail_eingang_id) REFERENCES mail_eingang(id) ON DELETE SET NULL;
alter table public.immobilie_eigentuemer add constraint immobilie_eigentuemer_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE CASCADE;
alter table public.immobilie_eigentuemer add constraint immobilie_eigentuemer_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.immobilie_fahrt_cache add constraint immobilie_fahrt_cache_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.immobilie_grundstueck add constraint immobilie_grundstueck_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.immobilie_kosten_einstellung add constraint immobilie_kosten_einstellung_aktualisiert_von_fkey FOREIGN KEY (aktualisiert_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.immobilie_kosten_einstellung add constraint immobilie_kosten_einstellung_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.immobilie_kosten_position add constraint immobilie_kosten_position_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.immobilie_kosten_position add constraint immobilie_kosten_position_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.immobilie_kosten_position add constraint immobilie_kosten_position_mitarbeiter_id_fkey FOREIGN KEY (mitarbeiter_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.immobilie_onedrive add constraint immobilie_onedrive_gesetzt_von_fkey FOREIGN KEY (gesetzt_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.immobilie_onedrive add constraint immobilie_onedrive_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.immobilie_portal_status add constraint immobilie_portal_status_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.immobilie_wissen add constraint immobilie_wissen_erstellt_von_fkey FOREIGN KEY (erstellt_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.immobilie_wissen add constraint immobilie_wissen_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.immobilien add constraint immobilien_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.immobilien add constraint immobilien_expose_titelbild_id_fkey FOREIGN KEY (expose_titelbild_id) REFERENCES immobilie_datei(id) ON DELETE SET NULL;
alter table public.immobilien add constraint immobilien_stammobjekt_id_fkey FOREIGN KEY (stammobjekt_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.immobilien add constraint immobilien_zustaendig_id_fkey FOREIGN KEY (zustaendig_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.ki_bildbearbeitung_log add constraint ki_bildbearbeitung_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.ki_pruefungen add constraint ki_pruefungen_erstellt_von_fkey FOREIGN KEY (erstellt_von) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.ki_pruefungen add constraint ki_pruefungen_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.kontakt_objekt add constraint kontakt_objekt_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kontakt_objekt add constraint kontakt_objekt_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.kontakt_objekt add constraint kontakt_objekt_kontakt_id_fkey FOREIGN KEY (kontakt_id) REFERENCES kontakte(id) ON DELETE CASCADE;
alter table public.kontakte add constraint kontakte_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE SET NULL;
alter table public.kontakte add constraint kontakte_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kontakte add constraint kontakte_zustaendig_id_fkey FOREIGN KEY (zustaendig_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kosten_saetze add constraint kosten_saetze_aktualisiert_von_fkey FOREIGN KEY (aktualisiert_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.liquid_imports add constraint liquid_imports_konto_id_fkey FOREIGN KEY (konto_id) REFERENCES liquid_konten(id) ON DELETE SET NULL;
alter table public.liquid_imports add constraint liquid_imports_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
alter table public.liquid_szenarien add constraint liquid_szenarien_konto_id_fkey FOREIGN KEY (konto_id) REFERENCES liquid_konten(id) ON DELETE SET NULL;
alter table public.liquid_transaktionen add constraint liquid_transaktionen_konto_id_fkey FOREIGN KEY (konto_id) REFERENCES liquid_konten(id) ON DELETE CASCADE;
alter table public.liquid_transaktionen add constraint liquid_transaktionen_umbuchung_partner_id_fkey FOREIGN KEY (umbuchung_partner_id) REFERENCES liquid_transaktionen(id) ON DELETE SET NULL;
alter table public.mail_absender_onedrive add constraint mail_absender_onedrive_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.mail_abwesenheit_log add constraint mail_abwesenheit_log_postfach_id_fkey FOREIGN KEY (postfach_id) REFERENCES mail_postfaecher(id) ON DELETE CASCADE;
alter table public.mail_eingang add constraint mail_eingang_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.mail_eingang add constraint mail_eingang_immobilie_id_ki_vorschlag_fkey FOREIGN KEY (immobilie_id_ki_vorschlag) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.mail_eingang add constraint mail_eingang_kontakt_id_fkey FOREIGN KEY (kontakt_id) REFERENCES kontakte(id) ON DELETE SET NULL;
alter table public.mail_eingang add constraint mail_eingang_mietanfrage_id_fkey FOREIGN KEY (mietanfrage_id) REFERENCES mietanfragen(id) ON DELETE SET NULL;
alter table public.mail_eingang add constraint mail_eingang_ordner_id_fkey FOREIGN KEY (ordner_id) REFERENCES mail_ordner(id) ON DELETE SET NULL;
alter table public.mail_eingang add constraint mail_eingang_postfach_id_fkey FOREIGN KEY (postfach_id) REFERENCES mail_postfaecher(id) ON DELETE CASCADE;
alter table public.mail_ki_log add constraint mail_ki_log_benutzer_id_fkey FOREIGN KEY (benutzer_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.mail_ki_log add constraint mail_ki_log_mail_eingang_id_fkey FOREIGN KEY (mail_eingang_id) REFERENCES mail_eingang(id) ON DELETE SET NULL;
alter table public.mail_ordner add constraint mail_ordner_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES mail_ordner(id) ON DELETE CASCADE;
alter table public.mail_ordner add constraint mail_ordner_postfach_id_fkey FOREIGN KEY (postfach_id) REFERENCES mail_postfaecher(id) ON DELETE CASCADE;
alter table public.mail_postfaecher add constraint mail_postfaecher_benutzer_id_fkey FOREIGN KEY (benutzer_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.mail_regeln add constraint mail_regeln_postfach_id_fkey FOREIGN KEY (postfach_id) REFERENCES mail_postfaecher(id) ON DELETE CASCADE;
alter table public.mail_versendet add constraint mail_versendet_mietanfrage_id_fkey FOREIGN KEY (mietanfrage_id) REFERENCES mietanfragen(id) ON DELETE SET NULL;
alter table public.mail_versendet add constraint mail_versendet_postfach_id_fkey FOREIGN KEY (postfach_id) REFERENCES mail_postfaecher(id) ON DELETE SET NULL;
alter table public.mail_versendet add constraint mail_versendet_versendet_von_user_id_fkey FOREIGN KEY (versendet_von_user_id) REFERENCES auth.users(id);
alter table public.mail_vorlagen add constraint mail_vorlagen_benutzer_id_fkey FOREIGN KEY (benutzer_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.marketing add constraint marketing_uploader_id_fkey FOREIGN KEY (uploader_id) REFERENCES profiles(id);
alter table public.marketing_print_vorlagen add constraint marketing_print_vorlagen_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.mietanfragen add constraint mietanfragen_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.mietanfragen add constraint mietanfragen_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.mietanfragen add constraint mietanfragen_mietvertrag_id_fkey FOREIGN KEY (mietvertrag_id) REFERENCES mietvertraege(id) ON DELETE SET NULL;
alter table public.mietanfragen add constraint mietanfragen_vertrag_id_fkey FOREIGN KEY (vertrag_id) REFERENCES vertraege(id) ON DELETE SET NULL;
alter table public.mietvertraege add constraint mietvertraege_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES auth.users(id);
alter table public.mietvertraege add constraint mietvertraege_ordner_id_fkey FOREIGN KEY (ordner_id) REFERENCES mietvertrag_ordner(id) ON DELETE SET NULL;
alter table public.mietvertrag_ordner add constraint mietvertrag_ordner_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id);
alter table public.notar_laufzettel add constraint notar_laufzettel_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.notiz_tags add constraint notiz_tags_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.notizen add constraint notizen_mail_id_fkey FOREIGN KEY (mail_id) REFERENCES mail_eingang(id) ON DELETE SET NULL;
alter table public.notizen add constraint notizen_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.objektaufnahme_fotos add constraint objektaufnahme_fotos_hochgeladen_von_user_id_fkey FOREIGN KEY (hochgeladen_von_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.objektaufnahme_fotos add constraint objektaufnahme_fotos_objektaufnahme_id_fkey FOREIGN KEY (objektaufnahme_id) REFERENCES objektaufnahmen(id) ON DELETE CASCADE;
alter table public.objektaufnahmen add constraint objektaufnahmen_bewertung_id_fkey FOREIGN KEY (bewertung_id) REFERENCES bewertungen(id) ON DELETE SET NULL;
alter table public.objektaufnahmen add constraint objektaufnahmen_erstellt_von_user_id_fkey FOREIGN KEY (erstellt_von_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.objektaufnahmen add constraint objektaufnahmen_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.objektaufnahmen add constraint objektaufnahmen_maklervertrag_id_fkey FOREIGN KEY (maklervertrag_id) REFERENCES vertraege(id) ON DELETE SET NULL;
alter table public.objektnachweise add constraint objektnachweise_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id);
alter table public.objektnachweise add constraint objektnachweise_maklervertrag_id_fkey FOREIGN KEY (maklervertrag_id) REFERENCES vertraege(id) ON DELETE SET NULL;
alter table public.onoffice_export_log add constraint onoffice_export_log_ausgeloest_von_fkey FOREIGN KEY (ausgeloest_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.onoffice_export_log add constraint onoffice_export_log_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.profiles add constraint profiles_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES firma_stammdaten(id);
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.projekt_aktivitaeten add constraint projekt_aktivitaeten_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_aktivitaeten add constraint projekt_aktivitaeten_zugang_id_fkey FOREIGN KEY (zugang_id) REFERENCES projekt_zugaenge(id) ON DELETE SET NULL;
alter table public.projekt_anfragen add constraint projekt_anfragen_einheit_id_fkey FOREIGN KEY (einheit_id) REFERENCES projekt_einheiten(id) ON DELETE CASCADE;
alter table public.projekt_anfragen add constraint projekt_anfragen_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_anfragen add constraint projekt_anfragen_zugang_id_fkey FOREIGN KEY (zugang_id) REFERENCES projekt_zugaenge(id) ON DELETE CASCADE;
alter table public.projekt_dateien add constraint projekt_dateien_einheit_id_fkey FOREIGN KEY (einheit_id) REFERENCES projekt_einheiten(id) ON DELETE CASCADE;
alter table public.projekt_dateien add constraint projekt_dateien_ordner_id_fkey FOREIGN KEY (ordner_id) REFERENCES projekt_ordner(id) ON DELETE SET NULL;
alter table public.projekt_dateien add constraint projekt_dateien_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_dateien add constraint projekt_dateien_zugang_id_fkey FOREIGN KEY (zugang_id) REFERENCES projekt_zugaenge(id) ON DELETE CASCADE;
alter table public.projekt_einheiten add constraint projekt_einheiten_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_kontakte add constraint projekt_kontakte_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_kunden_dateien add constraint projekt_kunden_dateien_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_kunden_dateien add constraint projekt_kunden_dateien_zugang_id_fkey FOREIGN KEY (zugang_id) REFERENCES projekt_zugaenge(id) ON DELETE CASCADE;
alter table public.projekt_maengel add constraint projekt_maengel_einheit_id_fkey FOREIGN KEY (einheit_id) REFERENCES projekt_einheiten(id) ON DELETE SET NULL;
alter table public.projekt_maengel add constraint projekt_maengel_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_maengel add constraint projekt_maengel_zugang_id_fkey FOREIGN KEY (zugang_id) REFERENCES projekt_zugaenge(id) ON DELETE CASCADE;
alter table public.projekt_merkliste add constraint projekt_merkliste_einheit_id_fkey FOREIGN KEY (einheit_id) REFERENCES projekt_einheiten(id) ON DELETE CASCADE;
alter table public.projekt_merkliste add constraint projekt_merkliste_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_merkliste add constraint projekt_merkliste_zugang_id_fkey FOREIGN KEY (zugang_id) REFERENCES projekt_zugaenge(id) ON DELETE CASCADE;
alter table public.projekt_nachrichten add constraint projekt_nachrichten_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_nachrichten add constraint projekt_nachrichten_zugang_id_fkey FOREIGN KEY (zugang_id) REFERENCES projekt_zugaenge(id) ON DELETE CASCADE;
alter table public.projekt_ordner add constraint projekt_ordner_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_updates add constraint projekt_updates_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_zahlungsplan add constraint projekt_zahlungsplan_einheit_id_fkey FOREIGN KEY (einheit_id) REFERENCES projekt_einheiten(id) ON DELETE SET NULL;
alter table public.projekt_zahlungsplan add constraint projekt_zahlungsplan_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.projekt_zahlungsplan add constraint projekt_zahlungsplan_zugang_id_fkey FOREIGN KEY (zugang_id) REFERENCES projekt_zugaenge(id) ON DELETE CASCADE;
alter table public.projekt_zugaenge add constraint projekt_zugaenge_ansprechpartner_id_fkey FOREIGN KEY (ansprechpartner_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.projekt_zugaenge add constraint projekt_zugaenge_einheit_id_fkey FOREIGN KEY (einheit_id) REFERENCES projekt_einheiten(id) ON DELETE SET NULL;
alter table public.projekt_zugaenge add constraint projekt_zugaenge_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE CASCADE;
alter table public.push_einstellungen add constraint push_einstellungen_aktualisiert_von_fkey FOREIGN KEY (aktualisiert_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.push_geraete add constraint push_geraete_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.push_log add constraint push_log_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.push_termin_erinnerungen add constraint push_termin_erinnerungen_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.push_termin_erinnerungen add constraint push_termin_erinnerungen_termin_id_fkey FOREIGN KEY (termin_id) REFERENCES termine(id) ON DELETE CASCADE;
alter table public.radar_aktivitaeten add constraint radar_aktivitaeten_benutzer_fkey FOREIGN KEY (benutzer) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.radar_aktivitaeten add constraint radar_aktivitaeten_objekt_id_fkey FOREIGN KEY (objekt_id) REFERENCES radar_objekte(id) ON DELETE CASCADE;
alter table public.radar_historie add constraint radar_historie_objekt_id_fkey FOREIGN KEY (objekt_id) REFERENCES radar_objekte(id) ON DELETE CASCADE;
alter table public.radar_objekte add constraint radar_objekte_erfasst_von_fkey FOREIGN KEY (erfasst_von) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.radar_objekte add constraint radar_objekte_zugeordnet_an_fkey FOREIGN KEY (zugeordnet_an) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.radar_suchauftraege add constraint radar_suchauftraege_benutzer_fkey FOREIGN KEY (benutzer) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.rechnung_nummern_sequence add constraint rechnung_nummern_sequence_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES firma_stammdaten(id);
alter table public.rechnung_positionen add constraint rechnung_positionen_rechnung_id_fkey FOREIGN KEY (rechnung_id) REFERENCES rechnungen(id) ON DELETE CASCADE;
alter table public.rechnungen add constraint rechnungen_absender_firma_id_fkey FOREIGN KEY (absender_firma_id) REFERENCES firma_stammdaten(id);
alter table public.rechnungen add constraint rechnungen_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id);
alter table public.rechnungen add constraint rechnungen_gestellt_durch_fkey FOREIGN KEY (gestellt_durch) REFERENCES profiles(id);
alter table public.rechnungen add constraint rechnungen_objektnachweis_id_fkey FOREIGN KEY (objektnachweis_id) REFERENCES objektnachweise(id);
alter table public.rechnungen add constraint rechnungen_storniert_durch_fkey FOREIGN KEY (storniert_durch) REFERENCES rechnungen(id);
alter table public.rechnungen add constraint rechnungen_storno_fuer_fkey FOREIGN KEY (storno_fuer) REFERENCES rechnungen(id);
alter table public.rechnungen add constraint rechnungen_vertrag_id_fkey FOREIGN KEY (vertrag_id) REFERENCES vertraege(id);
alter table public.rechnungen_audit add constraint rechnungen_audit_rechnung_id_fkey FOREIGN KEY (rechnung_id) REFERENCES rechnungen(id) ON DELETE CASCADE;
alter table public.rechnungen_audit add constraint rechnungen_audit_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
alter table public.reservierungen_neubau add constraint reservierungen_neubau_absender_firma_id_fkey FOREIGN KEY (absender_firma_id) REFERENCES firma_stammdaten(id);
alter table public.reservierungen_neubau add constraint reservierungen_neubau_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.reservierungen_neubau add constraint reservierungen_neubau_projekt_anfrage_id_fkey FOREIGN KEY (projekt_anfrage_id) REFERENCES projekt_anfragen(id) ON DELETE SET NULL;
alter table public.reservierungen_neubau add constraint reservierungen_neubau_projekt_einheit_id_fkey FOREIGN KEY (projekt_einheit_id) REFERENCES projekt_einheiten(id) ON DELETE SET NULL;
alter table public.reservierungen_neubau add constraint reservierungen_neubau_projekt_id_fkey FOREIGN KEY (projekt_id) REFERENCES projekte(id) ON DELETE SET NULL;
alter table public.reservierungen_neubau add constraint reservierungen_neubau_projekt_zugang_id_fkey FOREIGN KEY (projekt_zugang_id) REFERENCES projekt_zugaenge(id) ON DELETE SET NULL;
alter table public.reservierungen_neubau add constraint reservierungen_neubau_rechnung_id_fkey FOREIGN KEY (rechnung_id) REFERENCES rechnungen(id) ON DELETE SET NULL;
alter table public.rundgaenge add constraint rundgaenge_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.rundgaenge add constraint rundgaenge_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.rundgaenge add constraint rundgaenge_start_szene_id_fkey FOREIGN KEY (start_szene_id) REFERENCES rundgang_szenen(id) ON DELETE SET NULL;
alter table public.rundgang_hotspots add constraint rundgang_hotspots_szene_id_fkey FOREIGN KEY (szene_id) REFERENCES rundgang_szenen(id) ON DELETE CASCADE;
alter table public.rundgang_hotspots add constraint rundgang_hotspots_ziel_szene_id_fkey FOREIGN KEY (ziel_szene_id) REFERENCES rundgang_szenen(id) ON DELETE CASCADE;
alter table public.rundgang_szenen add constraint rundgang_szenen_rundgang_id_fkey FOREIGN KEY (rundgang_id) REFERENCES rundgaenge(id) ON DELETE CASCADE;
alter table public.signatur_empfaenger add constraint signatur_empfaenger_eigentuemer_person_id_fkey FOREIGN KEY (eigentuemer_person_id) REFERENCES eigentuemer_personen(id) ON DELETE SET NULL;
alter table public.signatur_empfaenger add constraint signatur_empfaenger_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.signatur_empfaenger add constraint signatur_empfaenger_vorgang_id_fkey FOREIGN KEY (vorgang_id) REFERENCES signatur_vorgaenge(id) ON DELETE CASCADE;
alter table public.signatur_events add constraint signatur_events_empfaenger_id_fkey FOREIGN KEY (empfaenger_id) REFERENCES signatur_empfaenger(id) ON DELETE CASCADE;
alter table public.signatur_events add constraint signatur_events_vorgang_id_fkey FOREIGN KEY (vorgang_id) REFERENCES signatur_vorgaenge(id) ON DELETE CASCADE;
alter table public.signatur_vorgaenge add constraint signatur_vorgaenge_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.suchkriterien_treffer add constraint suchkriterien_treffer_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.suchkriterien_treffer add constraint suchkriterien_treffer_kontakt_id_fkey FOREIGN KEY (kontakt_id) REFERENCES kontakte(id) ON DELETE CASCADE;
alter table public.termin_einladungen add constraint termin_einladungen_termin_id_fkey FOREIGN KEY (termin_id) REFERENCES termine(id) ON DELETE CASCADE;
alter table public.termine add constraint termine_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id);
alter table public.termine add constraint termine_fahrt_zu_termin_id_fkey FOREIGN KEY (fahrt_zu_termin_id) REFERENCES termine(id) ON DELETE CASCADE;
alter table public.termine add constraint termine_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.termine add constraint termine_kontakt_id_fkey FOREIGN KEY (kontakt_id) REFERENCES kontakte(id) ON DELETE SET NULL;
alter table public.termine add constraint termine_urlaub_entschieden_von_fkey FOREIGN KEY (urlaub_entschieden_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.todo_kommentar add constraint todo_kommentar_todo_id_fkey FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE CASCADE;
alter table public.todo_kommentar add constraint todo_kommentar_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.todo_schritt add constraint todo_schritt_todo_id_fkey FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE CASCADE;
alter table public.todo_verknuepfung add constraint todo_verknuepfung_todo_id_fkey FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE CASCADE;
alter table public.todo_vorgang add constraint todo_vorgang_gestartet_von_fkey FOREIGN KEY (gestartet_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.todo_vorgang add constraint todo_vorgang_vorlage_id_fkey FOREIGN KEY (vorlage_id) REFERENCES todo_vorlage(id) ON DELETE SET NULL;
alter table public.todo_vorlage_schritt add constraint todo_vorlage_schritt_vorlage_id_fkey FOREIGN KEY (vorlage_id) REFERENCES todo_vorlage(id) ON DELETE CASCADE;
alter table public.todos add constraint todos_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.todos add constraint todos_vorgang_fk FOREIGN KEY (vorgang_id) REFERENCES todo_vorgang(id) ON DELETE SET NULL;
alter table public.todos add constraint todos_wartet_auf_todo_id_fkey FOREIGN KEY (wartet_auf_todo_id) REFERENCES todos(id) ON DELETE SET NULL;
alter table public.todos add constraint todos_zustaendig_id_fkey FOREIGN KEY (zustaendig_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.uebergabeprotokoll add constraint uebergabeprotokoll_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.upload_benachrichtigungen add constraint upload_benachrichtigungen_ansprechpartner_id_fkey FOREIGN KEY (ansprechpartner_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.upload_benachrichtigungen add constraint upload_benachrichtigungen_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE CASCADE;
alter table public.urlaub_hinweise add constraint urlaub_hinweise_gesendet_von_fkey FOREIGN KEY (gesendet_von) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.urlaub_hinweise add constraint urlaub_hinweise_profil_id_fkey FOREIGN KEY (profil_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.verbrauchsausweis_antraege add constraint verbrauchsausweis_antraege_eigentuemer_id_fkey FOREIGN KEY (eigentuemer_id) REFERENCES eigentuemer(id) ON DELETE CASCADE;
alter table public.verbrauchsausweis_antraege add constraint verbrauchsausweis_antraege_erstellt_von_user_id_fkey FOREIGN KEY (erstellt_von_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.verbrauchsausweis_antraege add constraint verbrauchsausweis_antraege_maklervertrag_id_fkey FOREIGN KEY (maklervertrag_id) REFERENCES vertraege(id) ON DELETE SET NULL;
alter table public.verbrauchsausweis_antraege add constraint verbrauchsausweis_antraege_zip_dokument_id_fkey FOREIGN KEY (zip_dokument_id) REFERENCES eigentuemer_dokumente(id) ON DELETE SET NULL;
alter table public.vermerke add constraint vermerke_benutzer_id_fkey FOREIGN KEY (benutzer_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.vermerke add constraint vermerke_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE CASCADE;
alter table public.vermerke add constraint vermerke_kontakt_id_fkey FOREIGN KEY (kontakt_id) REFERENCES kontakte(id) ON DELETE CASCADE;
alter table public.vertraege add constraint vertraege_absender_firma_id_fkey FOREIGN KEY (absender_firma_id) REFERENCES firma_stammdaten(id);
alter table public.vertraege add constraint vertraege_ersteller_id_fkey FOREIGN KEY (ersteller_id) REFERENCES profiles(id);
alter table public.vertraege add constraint vertraege_immobilie_id_fkey FOREIGN KEY (immobilie_id) REFERENCES immobilien(id) ON DELETE SET NULL;
alter table public.web_leads add constraint web_leads_kontakt_id_fkey FOREIGN KEY (kontakt_id) REFERENCES kontakte(id);
