-- Indizes der Vorlage
--
-- Uebernommen aus der Vorlage, erzeugt von scripts/neutralisieren.py aus dem
-- woertlichen Schema-Export. Nicht von Hand aendern: die naechste Ausfuehrung
-- des Skripts wuerde die Aenderung verwerfen. Aenderungen gehoeren in das
-- Skript (mit Grund) oder in eine eigene, spaetere Migration.
--
-- Quelle: 28-indizes.sql
--
-- 243 Indizes ohne die, die an einem Constraint haengen.


CREATE INDEX akq_aktivitaeten_lead_idx ON public.akq_aktivitaeten USING btree (lead_id);
CREATE INDEX akq_aktivitaeten_offen_idx ON public.akq_aktivitaeten USING btree (erledigt_am, faellig_am);
CREATE INDEX akq_automation_lauf_lead_idx ON public.akq_automation_lauf USING btree (lead_id);
CREATE INDEX akq_automation_lauf_offen_idx ON public.akq_automation_lauf USING btree (status, geplant_fuer);
CREATE INDEX akq_automationen_stufe_idx ON public.akq_automationen USING btree (stufe_id);
CREATE INDEX akq_eingang_log_zeit_idx ON public.akq_eingang_log USING btree (created_at DESC);
CREATE INDEX akq_lead_historie_lead_idx ON public.akq_lead_historie USING btree (lead_id, created_at DESC);
CREATE INDEX akq_leads_created_idx ON public.akq_leads USING btree (created_at DESC);
CREATE INDEX akq_leads_kontakt_idx ON public.akq_leads USING btree (kontakt_id);
CREATE INDEX akq_leads_pipeline_idx ON public.akq_leads USING btree (pipeline_id);
CREATE INDEX akq_leads_status_idx ON public.akq_leads USING btree (status);
CREATE INDEX akq_leads_stufe_idx ON public.akq_leads USING btree (stufe_id);
CREATE INDEX akq_mail_leads_status_idx ON public.akq_mail_leads USING btree (status, gesendet_am DESC);
CREATE INDEX akq_stufen_pipeline_idx ON public.akq_stufen USING btree (pipeline_id, sortierung);
CREATE INDEX idx_aktiv_eigentuemer ON public.aktivitaeten USING btree (eigentuemer_id, created_at DESC);
CREATE INDEX idx_aktiv_ungelesen ON public.aktivitaeten USING btree (zielgruppe, gelesen_am) WHERE (gelesen_am IS NULL);
CREATE INDEX idx_aktiv_zielgruppe ON public.aktivitaeten USING btree (zielgruppe, created_at DESC);
CREATE INDEX aktivitaets_log_created_idx ON public.aktivitaets_log USING btree (created_at DESC);
CREATE INDEX aktivitaets_log_typ_idx ON public.aktivitaets_log USING btree (objekt_typ);
CREATE INDEX aktivitaets_log_user_idx ON public.aktivitaets_log USING btree (user_id);
CREATE INDEX idx_amt_typ_region ON public.amt_adressen USING btree (unterlagentyp, region_kanonisch);
CREATE UNIQUE INDEX arbeitszeit_modelle_profil_ab_idx ON public.arbeitszeit_modelle USING btree (profil_id, gueltig_ab);
CREATE INDEX arbeitszeit_stempel_profil_datum_idx ON public.arbeitszeit_stempel USING btree (profil_id, datum, zeitpunkt);
CREATE INDEX arbeitszeit_tage_datum_idx ON public.arbeitszeit_tage USING btree (datum);
CREATE UNIQUE INDEX arbeitszeit_tage_profil_datum_idx ON public.arbeitszeit_tage USING btree (profil_id, datum);
CREATE INDEX aufgaben_lead_idx ON public.aufgaben USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX aufgaben_status_idx ON public.aufgaben USING btree (status, zustaendig_id);
CREATE UNIQUE INDEX aufgaben_termin_typ_uidx ON public.aufgaben USING btree (termin_id, typ);
CREATE INDEX bewerber_einladungen_status_idx ON public.bewerber_einladungen USING btree (status);
CREATE INDEX bewertungen_akq_lead_idx ON public.bewertungen USING btree (akq_lead_id, created_at DESC) WHERE (akq_lead_id IS NOT NULL);
CREATE INDEX idx_bewertungen_immobilie ON public.bewertungen USING btree (immobilie_id);
CREATE INDEX idx_checkliste_items_anfrage_status ON public.checkliste_items USING btree (anfrage_status) WHERE (anfrage_status <> 'nicht_angefragt'::text);
CREATE INDEX idx_cli_vertrag ON public.checkliste_items USING btree (maklervertrag_id, sortierung);
CREATE INDEX idx_clvi_vorlage ON public.checkliste_vorlagen_items USING btree (vorlage_id, sortierung);
CREATE UNIQUE INDEX dashboard_gesehen_uidx ON public.dashboard_gesehen USING btree (benutzer_id, code, ref);
CREATE INDEX dashboard_gesehen_zeit_idx ON public.dashboard_gesehen USING btree (benutzer_id, gesehen_am DESC);
CREATE INDEX ea_orders_created_idx ON public.ea_orders USING btree (created_at DESC);
CREATE INDEX ea_orders_status_idx ON public.ea_orders USING btree (status);
CREATE INDEX idx_eigentuemer_aktiv_nicht_archiviert ON public.eigentuemer USING btree (created_at DESC) WHERE (archiviert_am IS NULL);
CREATE INDEX idx_eigentuemer_created_by ON public.eigentuemer USING btree (created_by);
CREATE INDEX idx_eigentuemer_email ON public.eigentuemer USING btree (lower(email));
CREATE INDEX idx_eigentuemer_portal_typ ON public.eigentuemer USING btree (portal_typ);
CREATE INDEX idx_eigentuemer_user ON public.eigentuemer USING btree (user_id);
CREATE UNIQUE INDEX idx_ebq_offen_einzigartig ON public.eigentuemer_benachrichtigung_queue USING btree (eigentuemer_id, ausloeser) WHERE (versendet_am IS NULL);
CREATE INDEX idx_ebq_zu_versenden ON public.eigentuemer_benachrichtigung_queue USING btree (letztes_ereignis_am) WHERE (versendet_am IS NULL);
CREATE INDEX eigentuemer_dokumente_antwort_auf_idx ON public.eigentuemer_dokumente USING btree (antwort_auf_dokument_id) WHERE (antwort_auf_dokument_id IS NOT NULL);
CREATE INDEX eigentuemer_dokumente_freigabe_status_idx ON public.eigentuemer_dokumente USING btree (freigabe_status) WHERE (freigabe_status = ANY (ARRAY['wartet_freigabe'::text, 'mit_anmerkungen'::text]));
CREATE INDEX idx_ed_checkliste ON public.eigentuemer_dokumente USING btree (checkliste_item_id);
CREATE INDEX idx_ed_eigentuemer ON public.eigentuemer_dokumente USING btree (eigentuemer_id, created_at DESC);
CREATE INDEX idx_ed_kategorie ON public.eigentuemer_dokumente USING btree (kategorie);
CREATE INDEX idx_ed_maklervertrag ON public.eigentuemer_dokumente USING btree (maklervertrag_id);
CREATE INDEX idx_einladung_status ON public.eigentuemer_einladungen USING btree (status);
CREATE INDEX idx_einladung_token ON public.eigentuemer_einladungen USING btree (token);
CREATE INDEX idx_eig_nachrichten_eig ON public.eigentuemer_nachrichten USING btree (eigentuemer_id, created_at);
CREATE INDEX idx_eo_eigentuemer ON public.eigentuemer_objekte USING btree (eigentuemer_id);
CREATE INDEX idx_eo_maklervertrag ON public.eigentuemer_objekte USING btree (maklervertrag_id);
CREATE INDEX idx_ep_eigentuemer ON public.eigentuemer_personen USING btree (eigentuemer_id);
CREATE INDEX idx_ep_email ON public.eigentuemer_personen USING btree (lower(email));
CREATE UNIQUE INDEX idx_ep_hauptperson_einzig ON public.eigentuemer_personen USING btree (eigentuemer_id) WHERE (ist_hauptperson = true);
CREATE INDEX idx_ep_user ON public.eigentuemer_personen USING btree (user_id);
CREATE INDEX ea_anfragen_created_idx ON public.energieausweis_anfragen USING btree (created_at DESC);
CREATE INDEX expose_entwuerfe_maklervertrag_idx ON public.expose_entwuerfe USING btree (maklervertrag_id);
CREATE INDEX expose_entwuerfe_updated_at_idx ON public.expose_entwuerfe USING btree (updated_at DESC);
CREATE INDEX expose_freigaben_email_idx ON public.expose_freigaben USING btree (lower(email));
CREATE INDEX expose_freigaben_immo_idx ON public.expose_freigaben USING btree (immobilie_id);
CREATE INDEX idx_credentials_audit_created ON public.external_credentials_audit USING btree (created_at);
CREATE INDEX idx_credentials_audit_credential ON public.external_credentials_audit USING btree (credential_id);
CREATE INDEX idx_credentials_audit_user ON public.external_credentials_audit USING btree (user_id);
CREATE INDEX fehler_protokoll_status_idx ON public.fehler_protokoll USING btree (status, created_at DESC);
CREATE INDEX fehler_protokoll_zeit_idx ON public.fehler_protokoll USING btree (created_at DESC);
CREATE UNIQUE INDEX firma_stammdaten_inhaber_uniq ON public.firma_stammdaten USING btree (inhaber_user_id) WHERE (typ = 'persoenlich'::text);
CREATE INDEX idx_immobilie_datei_imm ON public.immobilie_datei USING btree (immobilie_id);
CREATE INDEX immobilie_datei_expose_idx ON public.immobilie_datei USING btree (immobilie_id) WHERE (expose_ausschliessen = false);
CREATE UNIQUE INDEX immobilie_datei_onoffice_uniq ON public.immobilie_datei USING btree (immobilie_id, onoffice_datei_id) WHERE (onoffice_datei_id IS NOT NULL);
CREATE INDEX idx_immobilie_eigentuemer_eig ON public.immobilie_eigentuemer USING btree (eigentuemer_id);
CREATE INDEX idx_immobilie_eigentuemer_imm ON public.immobilie_eigentuemer USING btree (immobilie_id);
CREATE UNIQUE INDEX immobilie_kosten_position_auto_uidx ON public.immobilie_kosten_position USING btree (immobilie_id, typ, quelle_ref) WHERE (quelle = 'auto'::text);
CREATE INDEX immobilie_kosten_position_objekt_idx ON public.immobilie_kosten_position USING btree (immobilie_id, typ);
CREATE INDEX immobilie_wissen_immo_idx ON public.immobilie_wissen USING btree (immobilie_id);
CREATE UNIQUE INDEX immobilie_wissen_quelle_uidx ON public.immobilie_wissen USING btree (immobilie_id, quelle_ref);
CREATE INDEX idx_immobilien_status ON public.immobilien USING btree (status);
CREATE INDEX idx_immobilien_vertragsart ON public.immobilien USING btree (vertragsart);
CREATE INDEX idx_immobilien_zustaendig ON public.immobilien USING btree (zustaendig_id);
CREATE UNIQUE INDEX immobilien_immo_nr_key ON public.immobilien USING btree (immo_nr) WHERE ((immo_nr IS NOT NULL) AND (immo_nr <> ''::text));
CREATE UNIQUE INDEX immobilien_onoffice_id_uniq ON public.immobilien USING btree (onoffice_id);
CREATE INDEX immobilien_stammobjekt_idx ON public.immobilien USING btree (stammobjekt_id);
CREATE INDEX immobilien_versteckt_idx ON public.immobilien USING btree (versteckt) WHERE versteckt;
CREATE INDEX immobilien_website_idx ON public.immobilien USING btree (website_veroeffentlichen) WHERE (website_veroeffentlichen = true);
CREATE INDEX immobilien_zustaendig_id_idx ON public.immobilien USING btree (zustaendig_id);
CREATE INDEX ki_bildbearbeitung_log_created_idx ON public.ki_bildbearbeitung_log USING btree (created_at DESC);
CREATE INDEX ki_bildbearbeitung_log_funktion_idx ON public.ki_bildbearbeitung_log USING btree (funktion);
CREATE INDEX ki_bildbearbeitung_log_user_idx ON public.ki_bildbearbeitung_log USING btree (user_id);
CREATE INDEX ki_pruefungen_immobilie_idx ON public.ki_pruefungen USING btree (immobilie_id, created_at DESC);
CREATE INDEX kontakt_objekt_immo_idx ON public.kontakt_objekt USING btree (immobilie_id);
CREATE INDEX kontakt_objekt_kontakt_idx ON public.kontakt_objekt USING btree (kontakt_id);
CREATE INDEX kontakte_email_idx ON public.kontakte USING btree (lower(email));
CREATE INDEX kontakte_firma_idx ON public.kontakte USING btree (lower(firma));
CREATE INDEX kontakte_nachname_idx ON public.kontakte USING btree (lower(nachname));
CREATE UNIQUE INDEX kontakte_onoffice_id_uniq ON public.kontakte USING btree (onoffice_id);
CREATE INDEX kontakte_rollen_idx ON public.kontakte USING gin (rollen);
CREATE INDEX kontakte_zustaendig_idx ON public.kontakte USING btree (zustaendig_id);
CREATE INDEX liquid_kat_match_idx ON public.liquid_kategorisierung USING btree (match_key);
CREATE INDEX liquid_konten_firma_idx ON public.liquid_konten USING btree (firma);
CREATE INDEX liquid_szen_aktiv_idx ON public.liquid_szenarien USING btree (aktiv);
CREATE INDEX liquid_trans_datum_idx ON public.liquid_transaktionen USING btree (buchungsdatum DESC);
CREATE INDEX liquid_trans_firma_idx ON public.liquid_transaktionen USING btree (firma);
CREATE INDEX liquid_trans_gegenpartei_idx ON public.liquid_transaktionen USING btree (gegenpartei);
CREATE INDEX liquid_trans_kategorie_idx ON public.liquid_transaktionen USING btree (kategorie);
CREATE INDEX liquid_trans_konto_idx ON public.liquid_transaktionen USING btree (konto_id);
CREATE INDEX idx_mail_absender_onedrive_user_email ON public.mail_absender_onedrive USING btree (user_id, absender_email);
CREATE INDEX mail_abwesenheit_log_idx ON public.mail_abwesenheit_log USING btree (postfach_id, absender_email, gesendet_am);
CREATE INDEX idx_mail_eingang_anhaenge_status ON public.mail_eingang USING btree (anhaenge_status) WHERE (anhaenge_status <> 'unbekannt'::text);
CREATE INDEX idx_mail_eingang_gelesen ON public.mail_eingang USING btree (gelesen) WHERE (gelesen = false);
CREATE INDEX idx_mail_eingang_gesendet ON public.mail_eingang USING btree (gesendet_am DESC);
CREATE INDEX idx_mail_eingang_immobilie ON public.mail_eingang USING btree (immobilie_id);
CREATE UNIQUE INDEX idx_mail_eingang_msgid ON public.mail_eingang USING btree (postfach_id, message_id);
CREATE INDEX idx_mail_eingang_ordner ON public.mail_eingang USING btree (ordner_id);
CREATE INDEX idx_mail_eingang_postfach ON public.mail_eingang USING btree (postfach_id);
CREATE INDEX idx_mail_eingang_quelle ON public.mail_eingang USING btree (quelle);
CREATE INDEX mail_eingang_anfrage_offen_idx ON public.mail_eingang USING btree (gesendet_am DESC) WHERE ((anfrage_status IS NULL) AND (ordner = 'posteingang'::text));
CREATE INDEX mail_eingang_ordner_idx ON public.mail_eingang USING btree (ordner, gesendet_am DESC);
CREATE INDEX mail_eingang_postfach_ordner_idx ON public.mail_eingang USING btree (postfach_id, ordner, gesendet_am DESC);
CREATE INDEX mail_eingang_rechnung_offen_idx ON public.mail_eingang USING btree (gesendet_am DESC) WHERE ((rechnung_status IS NULL) AND (ordner = 'posteingang'::text));
CREATE INDEX mail_ki_log_user_idx ON public.mail_ki_log USING btree (benutzer_id, created_at DESC);
CREATE INDEX idx_mail_ordner_postfach ON public.mail_ordner USING btree (postfach_id);
CREATE INDEX idx_mail_ordner_typ ON public.mail_ordner USING btree (postfach_id, typ);
CREATE INDEX idx_mail_postfaecher_benutzer ON public.mail_postfaecher USING btree (benutzer_id);
CREATE UNIQUE INDEX mail_postfaecher_ein_standard_pro_user ON public.mail_postfaecher USING btree (benutzer_id) WHERE (ist_standard = true);
CREATE INDEX idx_mailversendet_anfrage ON public.mail_versendet USING btree (mietanfrage_id);
CREATE INDEX idx_mailversendet_user ON public.mail_versendet USING btree (versendet_von_user_id);
CREATE UNIQUE INDEX mail_vorlagen_onoffice_id_idx ON public.mail_vorlagen USING btree (onoffice_id) WHERE (onoffice_id IS NOT NULL);
CREATE INDEX idx_marketing_print_vorlagen_aktiv ON public.marketing_print_vorlagen USING btree (aktiv, kategorie, sortierung);
CREATE INDEX idx_mietanfragen_besichtigung ON public.mietanfragen USING btree (besichtigung_datum) WHERE (besichtigung_datum IS NOT NULL);
CREATE INDEX idx_mietanfragen_eingegangen ON public.mietanfragen USING btree (eingegangen_am DESC);
CREATE UNIQUE INDEX idx_mietanfragen_email_msgid ON public.mietanfragen USING btree (email_message_id) WHERE (email_message_id IS NOT NULL);
CREATE INDEX idx_mietanfragen_imap_uid ON public.mietanfragen USING btree (email_imap_uid) WHERE (email_imap_uid IS NOT NULL);
CREATE INDEX idx_mietanfragen_immobilie ON public.mietanfragen USING btree (immobilie_id);
CREATE INDEX idx_mietanfragen_jotform_submission ON public.mietanfragen USING btree (jotform_submission_id) WHERE (jotform_submission_id IS NOT NULL);
CREATE INDEX idx_mietanfragen_status ON public.mietanfragen USING btree (status);
CREATE INDEX idx_mietanfragen_vertrag ON public.mietanfragen USING btree (vertrag_id);
CREATE INDEX mietvertraege_created_at_idx ON public.mietvertraege USING btree (created_at DESC);
CREATE INDEX mietvertraege_ordner_idx ON public.mietvertraege USING btree (ordner_id);
CREATE INDEX idx_news_briefings_datum ON public.news_briefings USING btree (briefing_datum DESC);
CREATE INDEX idx_notar_laufzettel_created ON public.notar_laufzettel USING btree (created_at DESC);
CREATE INDEX idx_notar_laufzettel_status ON public.notar_laufzettel USING btree (status, created_at DESC);
CREATE INDEX idx_notar_onedrive_pfad ON public.notar_laufzettel USING btree (onedrive_ordner_pfad) WHERE (onedrive_ordner_pfad IS NOT NULL);
CREATE INDEX idx_notiz_tags_user ON public.notiz_tags USING btree (user_id);
CREATE INDEX idx_notizen_erledigt ON public.notizen USING btree (user_id, erledigt, erstellt_am DESC);
CREATE INDEX idx_notizen_mail_id ON public.notizen USING btree (mail_id) WHERE (mail_id IS NOT NULL);
CREATE INDEX idx_notizen_tags ON public.notizen USING gin (tags);
CREATE INDEX idx_notizen_text_fts ON public.notizen USING gin (to_tsvector('german'::regconfig, text));
CREATE INDEX idx_notizen_user_id ON public.notizen USING btree (user_id);
CREATE INDEX idx_objektaufnahme_fotos_aufnahme ON public.objektaufnahme_fotos USING btree (objektaufnahme_id);
CREATE INDEX idx_objektaufnahmen_immobilie ON public.objektaufnahmen USING btree (immobilie_id);
CREATE INDEX onoffice_adressen_art_idx ON public.onoffice_adressen USING btree (art_daten);
CREATE INDEX idx_onoffice_export_log_immobilie ON public.onoffice_export_log USING btree (immobilie_id);
CREATE INDEX idx_onoffice_objekte_aktiv ON public.onoffice_objekte USING btree (aktiv);
CREATE INDEX idx_onoffice_objekte_ort ON public.onoffice_objekte USING btree (ort);
CREATE INDEX idx_onoffice_objekte_vermarktung ON public.onoffice_objekte USING btree (vermarktungsart);
CREATE INDEX idx_onoffice_objekte_webseite ON public.onoffice_objekte USING btree (auf_webseite) WHERE auf_webseite;
CREATE INDEX idx_plz_region_plz ON public.plz_region USING btree (plz);
CREATE INDEX idx_plz_region_region ON public.plz_region USING btree (region);
CREATE INDEX profiles_firma_id_idx ON public.profiles USING btree (firma_id);
CREATE INDEX idx_projekt_aktivitaeten_projekt ON public.projekt_aktivitaeten USING btree (projekt_id, created_at DESC);
CREATE INDEX idx_projekt_anfragen_projekt ON public.projekt_anfragen USING btree (projekt_id, status);
CREATE INDEX idx_projekt_dateien_zugang ON public.projekt_dateien USING btree (zugang_id) WHERE (zugang_id IS NOT NULL);
CREATE INDEX idx_projekt_kunden_dateien_projekt ON public.projekt_kunden_dateien USING btree (projekt_id, created_at DESC);
CREATE INDEX idx_projekt_maengel_projekt ON public.projekt_maengel USING btree (projekt_id, status);
CREATE INDEX idx_projekt_merkliste_projekt ON public.projekt_merkliste USING btree (projekt_id);
CREATE INDEX idx_projekt_nachrichten_zugang ON public.projekt_nachrichten USING btree (zugang_id, created_at);
CREATE INDEX idx_projekt_ordner_projekt ON public.projekt_ordner USING btree (projekt_id, sortierung);
CREATE INDEX idx_projekt_zahlungsplan_zugang ON public.projekt_zahlungsplan USING btree (zugang_id, "position");
CREATE INDEX push_geraete_profil_idx ON public.push_geraete USING btree (profile_id) WHERE aktiv;
CREATE INDEX push_log_zeit_idx ON public.push_log USING btree (gesendet_am DESC);
CREATE INDEX radar_aktivitaeten_objekt_idx ON public.radar_aktivitaeten USING btree (objekt_id, datum DESC);
CREATE INDEX radar_historie_objekt_idx ON public.radar_historie USING btree (objekt_id, gesehen_am DESC);
CREATE INDEX radar_objekte_anbieter_idx ON public.radar_objekte USING btree (anbieter_typ);
CREATE UNIQUE INDEX radar_objekte_fingerprint_idx ON public.radar_objekte USING btree (fingerprint);
CREATE INDEX radar_objekte_gesehen_idx ON public.radar_objekte USING btree (zuletzt_gesehen DESC);
CREATE INDEX radar_objekte_ort_idx ON public.radar_objekte USING btree (plz, ort);
CREATE INDEX radar_objekte_status_idx ON public.radar_objekte USING btree (status) WHERE aktiv;
CREATE INDEX idx_rechnung_kunden_name ON public.rechnung_kunden USING btree (lower(name));
CREATE INDEX idx_rechnung_positionen_rechnung ON public.rechnung_positionen USING btree (rechnung_id);
CREATE INDEX idx_rechnungen_ausstellungsdatum ON public.rechnungen USING btree (ausstellungsdatum);
CREATE INDEX idx_rechnungen_firma ON public.rechnungen USING btree (absender_firma_id);
CREATE INDEX idx_rechnungen_objektnachweis ON public.rechnungen USING btree (objektnachweis_id);
CREATE INDEX idx_rechnungen_rechnungsnummer ON public.rechnungen USING btree (rechnungsnummer);
CREATE INDEX idx_rechnungen_status ON public.rechnungen USING btree (status);
CREATE INDEX idx_rechnungen_test ON public.rechnungen USING btree (ist_test);
CREATE INDEX idx_rechnungen_vertrag ON public.rechnungen USING btree (vertrag_id);
CREATE INDEX idx_rechnungen_audit_rechnung ON public.rechnungen_audit USING btree (rechnung_id);
CREATE INDEX idx_reservierungen_created ON public.reservierungen_neubau USING btree (created_at DESC);
CREATE INDEX idx_reservierungen_firma ON public.reservierungen_neubau USING btree (absender_firma_id);
CREATE INDEX idx_reservierungen_neubau_projekt ON public.reservierungen_neubau USING btree (projekt_id);
CREATE INDEX idx_reservierungen_status ON public.reservierungen_neubau USING btree (status);
CREATE INDEX rundgaenge_immobilie_idx ON public.rundgaenge USING btree (immobilie_id);
CREATE INDEX rundgaenge_token_idx ON public.rundgaenge USING btree (share_token) WHERE (share_token IS NOT NULL);
CREATE INDEX rundgang_hotspots_szene_idx ON public.rundgang_hotspots USING btree (szene_id);
CREATE INDEX rundgang_szenen_rundgang_idx ON public.rundgang_szenen USING btree (rundgang_id, sortierung);
CREATE INDEX idx_se_token ON public.signatur_empfaenger USING btree (token);
CREATE INDEX idx_se_vorgang ON public.signatur_empfaenger USING btree (vorgang_id);
CREATE INDEX idx_sev_vorgang ON public.signatur_events USING btree (vorgang_id);
CREATE INDEX idx_sv_status ON public.signatur_vorgaenge USING btree (status);
CREATE INDEX idx_sv_vertrag ON public.signatur_vorgaenge USING btree (vertrag_id);
CREATE INDEX suchkriterien_treffer_gemeldet ON public.suchkriterien_treffer USING btree (gemeldet_am) WHERE (gemeldet_am IS NULL);
CREATE INDEX suchkriterien_treffer_immobilie ON public.suchkriterien_treffer USING btree (immobilie_id);
CREATE INDEX termin_einladungen_termin_idx ON public.termin_einladungen USING btree (termin_id);
CREATE INDEX idx_termine_immobilie ON public.termine USING btree (immobilie_id);
CREATE INDEX termine_datum_idx ON public.termine USING btree (datum);
CREATE INDEX termine_erinnerung_idx ON public.termine USING btree (datum) WHERE ((kontakt_id IS NOT NULL) AND (erinnerung_status IS NULL));
CREATE UNIQUE INDEX termine_fahrt_eindeutig_idx ON public.termine USING btree (fahrt_zu_termin_id, fahrt_richtung) WHERE (fahrt_zu_termin_id IS NOT NULL);
CREATE INDEX termine_fahrt_zu_idx ON public.termine USING btree (fahrt_zu_termin_id);
CREATE INDEX termine_kontakt_idx ON public.termine USING btree (kontakt_id);
CREATE UNIQUE INDEX termine_onoffice_id_key ON public.termine USING btree (onoffice_id);
CREATE INDEX termine_quelle_idx ON public.termine USING btree (quelle);
CREATE INDEX termine_serie_idx ON public.termine USING btree (serie_id, datum) WHERE (serie_id IS NOT NULL);
CREATE INDEX todo_kommentar_idx ON public.todo_kommentar USING btree (todo_id, created_at);
CREATE INDEX todo_schritt_idx ON public.todo_schritt USING btree (todo_id, sortierung);
CREATE INDEX todo_verkn_ziel_idx ON public.todo_verknuepfung USING btree (objekt_typ, objekt_id);
CREATE INDEX todo_vorgang_bezug_idx ON public.todo_vorgang USING btree (bezug_typ, bezug_id);
CREATE INDEX todos_faellig_idx ON public.todos USING btree (faellig_am) WHERE (status = ANY (ARRAY['offen'::text, 'laeuft'::text, 'wartet'::text]));
CREATE INDEX todos_typ_idx ON public.todos USING btree (typ, status);
CREATE INDEX todos_vorgang_idx ON public.todos USING btree (vorgang_id) WHERE (vorgang_id IS NOT NULL);
CREATE UNIQUE INDEX todos_vorgang_schritt_uidx ON public.todos USING btree (vorgang_id, vorlage_schritt_id) WHERE ((vorgang_id IS NOT NULL) AND (vorlage_schritt_id IS NOT NULL));
CREATE INDEX todos_wartet_idx ON public.todos USING btree (wartet_auf_todo_id) WHERE (wartet_auf_todo_id IS NOT NULL);
CREATE INDEX todos_zustaendig_idx ON public.todos USING btree (zustaendig_id, status);
CREATE INDEX idx_uebergabeprotokoll_ersteller ON public.uebergabeprotokoll USING btree (ersteller_id, created_at DESC);
CREATE INDEX idx_uebergabeprotokoll_kontext ON public.uebergabeprotokoll USING btree (kontext, created_at DESC);
CREATE INDEX idx_uebergabeprotokoll_status ON public.uebergabeprotokoll USING btree (status, created_at DESC);
CREATE INDEX idx_upload_ben_eigentuemer ON public.upload_benachrichtigungen USING btree (eigentuemer_id, versendet_am);
CREATE INDEX idx_upload_ben_offen ON public.upload_benachrichtigungen USING btree (bereit_ab) WHERE (versendet_am IS NULL);
CREATE INDEX urlaub_hinweise_profil_idx ON public.urlaub_hinweise USING btree (profil_id, jahr);
CREATE INDEX va_eigentuemer_idx ON public.verbrauchsausweis_antraege USING btree (eigentuemer_id);
CREATE INDEX va_maklervertrag_idx ON public.verbrauchsausweis_antraege USING btree (maklervertrag_id);
CREATE INDEX va_status_idx ON public.verbrauchsausweis_antraege USING btree (status);
CREATE INDEX va_updated_idx ON public.verbrauchsausweis_antraege USING btree (updated_at DESC);
CREATE INDEX vermerke_immo_idx ON public.vermerke USING btree (immobilie_id, created_at DESC);
CREATE INDEX vermerke_kontakt_idx ON public.vermerke USING btree (kontakt_id, created_at DESC);
CREATE INDEX vermerke_telefonat_idx ON public.vermerke USING btree (immobilie_id, begonnen_am DESC) WHERE (typ = 'telefonat'::text);
CREATE INDEX vermerke_telefonat_kontakt_idx ON public.vermerke USING btree (kontakt_id, begonnen_am DESC) WHERE (typ = 'telefonat'::text);
CREATE INDEX vertraege_immobilie_idx ON public.vertraege USING btree (immobilie_id);
CREATE INDEX web_leads_created_idx ON public.web_leads USING btree (created_at DESC);
CREATE INDEX web_leads_status_idx ON public.web_leads USING btree (status);
